/*  C code generated by apiwrapper */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <ctype.h>
#include <errno.h>

#define GMO_MAIN
#include "gmomcc.h"

#if defined(_WIN32)
# include <windows.h>
  static char winErr[] = "Windows error";
  typedef HINSTANCE soHandle_t;
#else
# include <unistd.h>
# include <dlfcn.h>
# include <sys/utsname.h>
  typedef void *soHandle_t;
#endif

static soHandle_t h;
static int isLoaded = 0;
static int objectCount = 0;
static int ScreenIndicator = 1;
static int ExceptionIndicator = 0;
static int ExitIndicator = 1;
static gmoErrorCallback_t ErrorCallBack = NULL;
static int APIErrorCount = 0;

typedef void (GMO_CALLCONV *gmoXCreate_t) (gmoHandle_t *pgmo);
static GMO_FUNCPTR(gmoXCreate);
typedef void (GMO_CALLCONV *gmoXFree_t)   (gmoHandle_t *pgmo);
static GMO_FUNCPTR(gmoXFree);
typedef int (GMO_CALLCONV *gmoXAPIVersion_t) (int api, char *msg, int *cl);
static GMO_FUNCPTR(gmoXAPIVersion);
typedef int (GMO_CALLCONV *gmoXCheck_t) (const char *ep, int nargs, int s[], char *msg);
static GMO_FUNCPTR(gmoXCheck);

#define printNoReturn(f,nargs) { \
  char d_msgBuf[256]; \
  strcpy(d_msgBuf,#f " could not be loaded: "); \
  gmoXCheck(#f,nargs,d_s,d_msgBuf+strlen(d_msgBuf)); \
  gmoErrorHandling(d_msgBuf); \
}
#define printAndReturn(f,nargs,rtype) { \
  char d_msgBuf[256]; \
  strcpy(d_msgBuf,#f " could not be loaded: "); \
  gmoXCheck(#f,nargs,d_s,d_msgBuf+strlen(d_msgBuf)); \
  gmoErrorHandling(d_msgBuf); \
  return (rtype) 0; \
}

int  GMO_CALLCONV d_gmoLoadDataLegacy (gmoHandle_t pgmo, char *msg)
{ int d_s[]={3,12}; printAndReturn(gmoLoadDataLegacy,1,int ) }

int  GMO_CALLCONV d_gmoInitData (gmoHandle_t pgmo, int rows, int cols)
{ int d_s[]={3,3,3}; printAndReturn(gmoInitData,2,int ) }

int  GMO_CALLCONV d_gmoCompleteData (gmoHandle_t pgmo, const char *instname, char *msg)
{ int d_s[]={3,11,12}; printAndReturn(gmoCompleteData,2,int ) }

int  GMO_CALLCONV d_gmoGetObjQ (gmoHandle_t pgmo, int colIdx[], int rowIdx[], double coef[])
{ int d_s[]={3,8,8,6}; printAndReturn(gmoGetObjQ,3,int ) }

int  GMO_CALLCONV d_gmoGetRowQ (gmoHandle_t pgmo, int si, int colIdx[], int rowIdx[], double coef[])
{ int d_s[]={3,3,8,8,6}; printAndReturn(gmoGetRowQ,4,int ) }

int  GMO_CALLCONV d_gmoDumpQMakerGDX (gmoHandle_t pgmo, const char *gdxfname)
{ int d_s[]={3,11}; printAndReturn(gmoDumpQMakerGDX,1,int ) }

int  GMO_CALLCONV d_gmoGetColStat (gmoHandle_t pgmo, int sj, int *jnz, int *jqnz, int *jnlnz, int *jobjnz)
{ int d_s[]={3,3,4,4,4,4}; printAndReturn(gmoGetColStat,5,int ) }

int  GMO_CALLCONV d_gmoGetObjStat (gmoHandle_t pgmo, int *inz, int *iqnz, int *inlnz)
{ int d_s[]={3,4,4,4}; printAndReturn(gmoGetObjStat,3,int ) }

int  GMO_CALLCONV d_gmoGetRowStat (gmoHandle_t pgmo, int si, int *inz, int *iqnz, int *inlnz)
{ int d_s[]={3,3,4,4,4}; printAndReturn(gmoGetRowStat,4,int ) }

int  GMO_CALLCONV d_gmoGetMatrixCplex (gmoHandle_t pgmo, int ColStart[], int ColLength[], int RowIndex[], double JacValue[])
{ int d_s[]={3,8,8,8,6}; printAndReturn(gmoGetMatrixCplex,4,int ) }

int  GMO_CALLCONV d_gmoGetMatrixCol (gmoHandle_t pgmo, int ColStart[], int RowIndex[], double JacValue[], int NLFlag[])
{ int d_s[]={3,8,8,6,8}; printAndReturn(gmoGetMatrixCol,4,int ) }

int  GMO_CALLCONV d_gmoGetObjVector (gmoHandle_t pgmo, double ObjVector[], int NLFlag[])
{ int d_s[]={3,6,8}; printAndReturn(gmoGetObjVector,2,int ) }

int  GMO_CALLCONV d_gmoGetObjSparse (gmoHandle_t pgmo, int ColIndex[], double JacValue[], int NLFlag[], int *NZ, int *NLNZ)
{ int d_s[]={3,8,6,8,4,4}; printAndReturn(gmoGetObjSparse,5,int ) }

int  GMO_CALLCONV d_gmoGetRowSparse (gmoHandle_t pgmo, int si, int ColIndex[], double JacValue[], int NLFlag[], int *NZ, int *NLNZ)
{ int d_s[]={3,3,8,6,8,4,4}; printAndReturn(gmoGetRowSparse,6,int ) }

int  GMO_CALLCONV d_gmoGetColSparse (gmoHandle_t pgmo, int sj, int RowIndex[], double JacValue[], int NLFlag[], int *NZ, int *NLNZ)
{ int d_s[]={3,3,8,6,8,4,4}; printAndReturn(gmoGetColSparse,6,int ) }

int  GMO_CALLCONV d_gmoGetMatrixRow (gmoHandle_t pgmo, int RowStart[], int ColIndex[], double JacValue[], int NLFlag[])
{ int d_s[]={3,8,8,6,8}; printAndReturn(gmoGetMatrixRow,4,int ) }

void  GMO_CALLCONV d_gmoGetSosCounts (gmoHandle_t pgmo, int *numSos1, int *numSos2, int *nzSos)
{ int d_s[]={0,4,4,4}; printNoReturn(gmoGetSosCounts,3) }

int  GMO_CALLCONV d_gmoGetSosConstraints (gmoHandle_t pgmo, int sostype[], int sosbeg[], int sosind[], double soswt[])
{ int d_s[]={3,8,8,8,6}; printAndReturn(gmoGetSosConstraints,4,int ) }

int  GMO_CALLCONV d_gmoGetVarSosSetOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={3,3}; printAndReturn(gmoGetVarSosSetOne,1,int ) }

void  GMO_CALLCONV d_gmoGetColJacInfoOne (gmoHandle_t pgmo, int sj, void **jacp, double *aval, int *irow, int *nzind)
{ int d_s[]={0,3,2,14,4,4}; printNoReturn(gmoGetColJacInfoOne,5) }

void  GMO_CALLCONV d_gmoGetRowJacInfoOne (gmoHandle_t pgmo, int si, void **jacp, double *aval, int *jcol, int *nzind)
{ int d_s[]={0,3,2,14,4,4}; printNoReturn(gmoGetRowJacInfoOne,5) }

int  GMO_CALLCONV d_gmoGetVarL (gmoHandle_t pgmo, double X[])
{ int d_s[]={3,6}; printAndReturn(gmoGetVarL,1,int ) }

double  GMO_CALLCONV d_gmoGetVarLOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={13,3}; printAndReturn(gmoGetVarLOne,1,double ) }

int  GMO_CALLCONV d_gmoSetVarL (gmoHandle_t pgmo, const double X[])
{ int d_s[]={3,5}; printAndReturn(gmoSetVarL,1,int ) }

void  GMO_CALLCONV d_gmoSetVarLOne (gmoHandle_t pgmo, int sj, double value)
{ int d_s[]={0,3,13}; printNoReturn(gmoSetVarLOne,2) }

int  GMO_CALLCONV d_gmoGetVarM (gmoHandle_t pgmo, double Dj[])
{ int d_s[]={3,6}; printAndReturn(gmoGetVarM,1,int ) }

double  GMO_CALLCONV d_gmoGetVarMOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={13,3}; printAndReturn(gmoGetVarMOne,1,double ) }

int  GMO_CALLCONV d_gmoSetVarM (gmoHandle_t pgmo, const double Dj[])
{ int d_s[]={3,5}; printAndReturn(gmoSetVarM,1,int ) }

char * GMO_CALLCONV d_gmoGetVarNameOne (gmoHandle_t pgmo, int sj, char *buf)
{ int d_s[]={12,3}; printAndReturn(gmoGetVarNameOne,1,char *) }

char * GMO_CALLCONV d_gmoGetVarNameCustomOne (gmoHandle_t pgmo, int sj, const char *suffix, char *buf)
{ int d_s[]={12,3,11}; printAndReturn(gmoGetVarNameCustomOne,2,char *) }

int  GMO_CALLCONV d_gmoGetVarLower (gmoHandle_t pgmo, double LoVector[])
{ int d_s[]={3,6}; printAndReturn(gmoGetVarLower,1,int ) }

double  GMO_CALLCONV d_gmoGetVarLowerOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={13,3}; printAndReturn(gmoGetVarLowerOne,1,double ) }

int  GMO_CALLCONV d_gmoGetVarUpper (gmoHandle_t pgmo, double UpVector[])
{ int d_s[]={3,6}; printAndReturn(gmoGetVarUpper,1,int ) }

double  GMO_CALLCONV d_gmoGetVarUpperOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={13,3}; printAndReturn(gmoGetVarUpperOne,1,double ) }

int  GMO_CALLCONV d_gmoSetAltVarBounds (gmoHandle_t pgmo, const double LoVector[], const double UpVector[])
{ int d_s[]={3,5,5}; printAndReturn(gmoSetAltVarBounds,2,int ) }

void  GMO_CALLCONV d_gmoSetAltVarLowerOne (gmoHandle_t pgmo, int sj, double value)
{ int d_s[]={0,3,13}; printNoReturn(gmoSetAltVarLowerOne,2) }

void  GMO_CALLCONV d_gmoSetAltVarUpperOne (gmoHandle_t pgmo, int sj, double value)
{ int d_s[]={0,3,13}; printNoReturn(gmoSetAltVarUpperOne,2) }

int  GMO_CALLCONV d_gmoGetVarType (gmoHandle_t pgmo, int TypeVector[])
{ int d_s[]={3,8}; printAndReturn(gmoGetVarType,1,int ) }

int  GMO_CALLCONV d_gmoGetVarTypeOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={3,3}; printAndReturn(gmoGetVarTypeOne,1,int ) }

int  GMO_CALLCONV d_gmoSetAltVarType (gmoHandle_t pgmo, const int TypeVector[])
{ int d_s[]={3,7}; printAndReturn(gmoSetAltVarType,1,int ) }

void  GMO_CALLCONV d_gmoSetAltVarTypeOne (gmoHandle_t pgmo, int sj, int value)
{ int d_s[]={0,3,3}; printNoReturn(gmoSetAltVarTypeOne,2) }

int  GMO_CALLCONV d_gmoGetVarTypeCnt (gmoHandle_t pgmo, int vart)
{ int d_s[]={3,3}; printAndReturn(gmoGetVarTypeCnt,1,int ) }

void  GMO_CALLCONV d_gmoGetVarStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoGetVarStat,1) }

int  GMO_CALLCONV d_gmoGetVarStatOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={3,3}; printAndReturn(gmoGetVarStatOne,1,int ) }

void  GMO_CALLCONV d_gmoSetVarStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoSetVarStat,1) }

void  GMO_CALLCONV d_gmoSetVarStatOne (gmoHandle_t pgmo, int sj, int value)
{ int d_s[]={0,3,3}; printNoReturn(gmoSetVarStatOne,2) }

void  GMO_CALLCONV d_gmoGetVarCStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoGetVarCStat,1) }

int  GMO_CALLCONV d_gmoGetVarCStatOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={3,3}; printAndReturn(gmoGetVarCStatOne,1,int ) }

void  GMO_CALLCONV d_gmoSetVarCStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoSetVarCStat,1) }

int  GMO_CALLCONV d_gmoBasisIsFull (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoBasisIsFull,0,int ) }

int  GMO_CALLCONV d_gmoGetVarPrior (gmoHandle_t pgmo, double BranchPrior[])
{ int d_s[]={3,6}; printAndReturn(gmoGetVarPrior,1,int ) }

double  GMO_CALLCONV d_gmoGetVarPriorOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={13,3}; printAndReturn(gmoGetVarPriorOne,1,double ) }

int  GMO_CALLCONV d_gmoGetVarScale (gmoHandle_t pgmo, double ScaleVector[])
{ int d_s[]={3,6}; printAndReturn(gmoGetVarScale,1,int ) }

double  GMO_CALLCONV d_gmoGetVarScaleOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={13,3}; printAndReturn(gmoGetVarScaleOne,1,double ) }

double  GMO_CALLCONV d_gmoGetVarStageOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={13,3}; printAndReturn(gmoGetVarStageOne,1,double ) }

int  GMO_CALLCONV d_gmoGetEquL (gmoHandle_t pgmo, double Mvector[])
{ int d_s[]={3,6}; printAndReturn(gmoGetEquL,1,int ) }

double  GMO_CALLCONV d_gmoGetEquLOne (gmoHandle_t pgmo, int si)
{ int d_s[]={13,3}; printAndReturn(gmoGetEquLOne,1,double ) }

int  GMO_CALLCONV d_gmoSetEquL (gmoHandle_t pgmo, const double Mvector[])
{ int d_s[]={3,5}; printAndReturn(gmoSetEquL,1,int ) }

int  GMO_CALLCONV d_gmoGetEquM (gmoHandle_t pgmo, double PI[])
{ int d_s[]={3,6}; printAndReturn(gmoGetEquM,1,int ) }

double  GMO_CALLCONV d_gmoGetEquMOne (gmoHandle_t pgmo, int si)
{ int d_s[]={13,3}; printAndReturn(gmoGetEquMOne,1,double ) }

int  GMO_CALLCONV d_gmoSetEquM (gmoHandle_t pgmo, const double PI[])
{ int d_s[]={3,5}; printAndReturn(gmoSetEquM,1,int ) }

char * GMO_CALLCONV d_gmoGetEquNameOne (gmoHandle_t pgmo, int si, char *buf)
{ int d_s[]={12,3}; printAndReturn(gmoGetEquNameOne,1,char *) }

char * GMO_CALLCONV d_gmoGetEquNameCustomOne (gmoHandle_t pgmo, int si, const char *suffix, char *buf)
{ int d_s[]={12,3,11}; printAndReturn(gmoGetEquNameCustomOne,2,char *) }

char * GMO_CALLCONV d_gmoGetObjName (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoGetObjName,0,char *) }

char * GMO_CALLCONV d_gmoGetObjNameCustom (gmoHandle_t pgmo, const char *suffix, char *buf)
{ int d_s[]={12,11}; printAndReturn(gmoGetObjNameCustom,1,char *) }

int  GMO_CALLCONV d_gmoGetRhs (gmoHandle_t pgmo, double RhsVector[])
{ int d_s[]={3,6}; printAndReturn(gmoGetRhs,1,int ) }

double  GMO_CALLCONV d_gmoGetRhsOne (gmoHandle_t pgmo, int si)
{ int d_s[]={13,3}; printAndReturn(gmoGetRhsOne,1,double ) }

int  GMO_CALLCONV d_gmoSetAltRHS (gmoHandle_t pgmo, const double RhsVector[])
{ int d_s[]={3,5}; printAndReturn(gmoSetAltRHS,1,int ) }

void  GMO_CALLCONV d_gmoSetAltRHSOne (gmoHandle_t pgmo, int si, double value)
{ int d_s[]={0,3,13}; printNoReturn(gmoSetAltRHSOne,2) }

int  GMO_CALLCONV d_gmoGetEquSlack (gmoHandle_t pgmo, double Mvector[])
{ int d_s[]={3,6}; printAndReturn(gmoGetEquSlack,1,int ) }

double  GMO_CALLCONV d_gmoGetEquSlackOne (gmoHandle_t pgmo, int si)
{ int d_s[]={13,3}; printAndReturn(gmoGetEquSlackOne,1,double ) }

int  GMO_CALLCONV d_gmoSetEquSlack (gmoHandle_t pgmo, const double Mvector[])
{ int d_s[]={3,5}; printAndReturn(gmoSetEquSlack,1,int ) }

int  GMO_CALLCONV d_gmoGetEquType (gmoHandle_t pgmo, int TypeVector[])
{ int d_s[]={3,8}; printAndReturn(gmoGetEquType,1,int ) }

int  GMO_CALLCONV d_gmoGetEquTypeOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetEquTypeOne,1,int ) }

int  GMO_CALLCONV d_gmoGetEquTypeCnt (gmoHandle_t pgmo, int equt)
{ int d_s[]={3,3}; printAndReturn(gmoGetEquTypeCnt,1,int ) }

void  GMO_CALLCONV d_gmoGetEquStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoGetEquStat,1) }

int  GMO_CALLCONV d_gmoGetEquStatOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetEquStatOne,1,int ) }

void  GMO_CALLCONV d_gmoSetEquStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoSetEquStat,1) }

void  GMO_CALLCONV d_gmoGetEquCStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoGetEquCStat,1) }

int  GMO_CALLCONV d_gmoGetEquCStatOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetEquCStatOne,1,int ) }

void  GMO_CALLCONV d_gmoSetEquCStat (gmoHandle_t pgmo, int StatVector[])
{ int d_s[]={0,8}; printNoReturn(gmoSetEquCStat,1) }

int  GMO_CALLCONV d_gmoGetEquMatch (gmoHandle_t pgmo, int matchVector[])
{ int d_s[]={3,8}; printAndReturn(gmoGetEquMatch,1,int ) }

int  GMO_CALLCONV d_gmoGetEquMatchOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetEquMatchOne,1,int ) }

int  GMO_CALLCONV d_gmoGetEquScale (gmoHandle_t pgmo, double ScaleVector[])
{ int d_s[]={3,6}; printAndReturn(gmoGetEquScale,1,int ) }

double  GMO_CALLCONV d_gmoGetEquScaleOne (gmoHandle_t pgmo, int si)
{ int d_s[]={13,3}; printAndReturn(gmoGetEquScaleOne,1,double ) }

double  GMO_CALLCONV d_gmoGetEquStageOne (gmoHandle_t pgmo, int si)
{ int d_s[]={13,3}; printAndReturn(gmoGetEquStageOne,1,double ) }

int  GMO_CALLCONV d_gmoGetEquOrderOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetEquOrderOne,1,int ) }

int  GMO_CALLCONV d_gmoGetRowQNZOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetRowQNZOne,1,int ) }

int  GMO_CALLCONV d_gmoGetRowQDiagNZOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetRowQDiagNZOne,1,int ) }

void  GMO_CALLCONV d_gmoGetXLibCounts (gmoHandle_t pgmo, int *x_rows, int *x_cols, int *x_nzs, int orgcolind[])
{ int d_s[]={0,4,4,4,8}; printNoReturn(gmoGetXLibCounts,4) }

double  GMO_CALLCONV d_gmoGetHeadnTail (gmoHandle_t pgmo, int headrec)
{ int d_s[]={13,3}; printAndReturn(gmoGetHeadnTail,1,double ) }

void  GMO_CALLCONV d_gmoSetHeadnTail (gmoHandle_t pgmo, int headrec, double value)
{ int d_s[]={0,3,13}; printNoReturn(gmoSetHeadnTail,2) }

int  GMO_CALLCONV d_gmoSetEquPermutation (gmoHandle_t pgmo, int permut[])
{ int d_s[]={3,8}; printAndReturn(gmoSetEquPermutation,1,int ) }

int  GMO_CALLCONV d_gmoSetRvEquPermutation (gmoHandle_t pgmo, int rvpermut[], int len)
{ int d_s[]={3,8,3}; printAndReturn(gmoSetRvEquPermutation,2,int ) }

int  GMO_CALLCONV d_gmoSetVarPermutation (gmoHandle_t pgmo, int permut[])
{ int d_s[]={3,8}; printAndReturn(gmoSetVarPermutation,1,int ) }

int  GMO_CALLCONV d_gmoSetRvVarPermutation (gmoHandle_t pgmo, int rvpermut[], int len)
{ int d_s[]={3,8,3}; printAndReturn(gmoSetRvVarPermutation,2,int ) }

int  GMO_CALLCONV d_gmoSetNRowPerm (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoSetNRowPerm,0,int ) }

int  GMO_CALLCONV d_gmoDirtyExtractDefVar (gmoHandle_t pgmo, int *rowPiv, int *rowFree, int *colFix, int ColNO[], int RowNO[], double DefPiv[])
{ int d_s[]={3,4,4,4,8,8,6}; printAndReturn(gmoDirtyExtractDefVar,6,int ) }

int  GMO_CALLCONV d_gmoSetSolution2 (gmoHandle_t pgmo, const double X[], const double PI[])
{ int d_s[]={3,5,5}; printAndReturn(gmoSetSolution2,2,int ) }

int  GMO_CALLCONV d_gmoSetSolution (gmoHandle_t pgmo, const double X[], const double Dj[], const double PI[], const double E[])
{ int d_s[]={3,5,5,5,5}; printAndReturn(gmoSetSolution,4,int ) }

int  GMO_CALLCONV d_gmoSetSolution8 (gmoHandle_t pgmo, const double X[], const double Dj[], const double PI[], const double E[], int XB[], int XS[], int YB[], int YS[])
{ int d_s[]={3,5,5,5,5,8,8,8,8}; printAndReturn(gmoSetSolution8,8,int ) }

int  GMO_CALLCONV d_gmoSetSolutionFixer (gmoHandle_t pgmo, int modelStatHint, const double X[], const double PI[], const int XB[], const int YB[])
{ int d_s[]={3,3,5,5,7,7}; printAndReturn(gmoSetSolutionFixer,5,int ) }

int  GMO_CALLCONV d_gmoGetSolutionVarRec (gmoHandle_t pgmo, int sj, double *X, double *Dj, int *XB, int *XS)
{ int d_s[]={3,3,14,14,4,4}; printAndReturn(gmoGetSolutionVarRec,5,int ) }

int  GMO_CALLCONV d_gmoSetSolutionVarRec (gmoHandle_t pgmo, int sj, double X, double Dj, int XB, int XS)
{ int d_s[]={3,3,13,13,3,3}; printAndReturn(gmoSetSolutionVarRec,5,int ) }

int  GMO_CALLCONV d_gmoGetSolutionEquRec (gmoHandle_t pgmo, int si, double *E, double *PI, int *YB, int *YS)
{ int d_s[]={3,3,14,14,4,4}; printAndReturn(gmoGetSolutionEquRec,5,int ) }

int  GMO_CALLCONV d_gmoSetSolutionEquRec (gmoHandle_t pgmo, int si, double E, double PI, int YB, int YS)
{ int d_s[]={3,3,13,13,3,3}; printAndReturn(gmoSetSolutionEquRec,5,int ) }

int  GMO_CALLCONV d_gmoSetSolutionStatus (gmoHandle_t pgmo, int XB[], int XS[], int YB[], int YS[])
{ int d_s[]={3,8,8,8,8}; printAndReturn(gmoSetSolutionStatus,4,int ) }

int  GMO_CALLCONV d_gmoCompleteSolution (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoCompleteSolution,0,int ) }

int  GMO_CALLCONV d_gmoLoadSolutionLegacy (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoLoadSolutionLegacy,0,int ) }

int  GMO_CALLCONV d_gmoUnloadSolutionLegacy (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoUnloadSolutionLegacy,0,int ) }

int  GMO_CALLCONV d_gmoLoadSolutionGDX (gmoHandle_t pgmo, const char *gdxfname, int rows, int cols, int ht)
{ int d_s[]={3,11,15,15,15}; printAndReturn(gmoLoadSolutionGDX,4,int ) }

int  GMO_CALLCONV d_gmoUnloadSolutionGDX (gmoHandle_t pgmo, const char *gdxfname, int rows, int cols, int ht)
{ int d_s[]={3,11,15,15,15}; printAndReturn(gmoUnloadSolutionGDX,4,int ) }

int  GMO_CALLCONV d_gmoLastError (gmoHandle_t pgmo, char *msg)
{ int d_s[]={3,12}; printAndReturn(gmoLastError,1,int ) }

void  GMO_CALLCONV d_gmoClearError (gmoHandle_t pgmo)
{ int d_s[]={0}; printNoReturn(gmoClearError,0) }

double  GMO_CALLCONV d_gmoMemUsed (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoMemUsed,0,double ) }

double  GMO_CALLCONV d_gmoPeakMemUsed (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoPeakMemUsed,0,double ) }

int  GMO_CALLCONV d_gmoGetiSolver (gmoHandle_t pgmo, int mi)
{ int d_s[]={3,3}; printAndReturn(gmoGetiSolver,1,int ) }

int  GMO_CALLCONV d_gmoGetjSolver (gmoHandle_t pgmo, int mj)
{ int d_s[]={3,3}; printAndReturn(gmoGetjSolver,1,int ) }

int  GMO_CALLCONV d_gmoGetiModel (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetiModel,1,int ) }

int  GMO_CALLCONV d_gmoGetjModel (gmoHandle_t pgmo, int sj)
{ int d_s[]={3,3}; printAndReturn(gmoGetjModel,1,int ) }

int  GMO_CALLCONV d_gmoAddRow (gmoHandle_t pgmo, int typEqu, int matchEqu, double slackEqu, double scaleEqu, double rhsEqu, double mEqu, int basEqu, int nzEqu, const int colArr[], const double jacArr[], const int nlArr[])
{ int d_s[]={3,3,3,13,13,13,13,3,3,7,5,7}; printAndReturn(gmoAddRow,11,int ) }

int  GMO_CALLCONV d_gmoAddCol (gmoHandle_t pgmo, int typVar, double loVar, double lVar, double upVar, double mVar, int basVar, int sosVar, double priorVar, double scaleVar, int nzVar, const int rowArr[], const double jacArr[], const int nlArr[])
{ int d_s[]={3,3,13,13,13,13,3,3,13,13,3,7,5,7}; printAndReturn(gmoAddCol,13,int ) }

void  GMO_CALLCONV d_gmoCompleteJacs (gmoHandle_t pgmo)
{ int d_s[]={0}; printNoReturn(gmoCompleteJacs,0) }

int  GMO_CALLCONV d_gmoCrudeness (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoCrudeness,0,int ) }

void * GMO_CALLCONV d_gmoDict (gmoHandle_t pgmo)
{ int d_s[]={1}; printAndReturn(gmoDict,0,void *) }

void  GMO_CALLCONV d_gmoSetDictObject (gmoHandle_t pgmo, void *DictObj)
{ int d_s[]={0,1}; printNoReturn(gmoSetDictObject,1) }

void * GMO_CALLCONV d_gmoEnvironment (gmoHandle_t pgmo)
{ int d_s[]={1}; printAndReturn(gmoEnvironment,0,void *) }

int  GMO_CALLCONV d_gmoRegisterEnvironment (gmoHandle_t pgmo, void *gevPtr, char *msg)
{ int d_s[]={3,1,12}; printAndReturn(gmoRegisterEnvironment,2,int ) }

int  GMO_CALLCONV d_gmoGetVarTypeTxt (gmoHandle_t pgmo, int sj, char *vartypetxt)
{ int d_s[]={3,3,12}; printAndReturn(gmoGetVarTypeTxt,2,int ) }

int  GMO_CALLCONV d_gmoGetEquTypeTxt (gmoHandle_t pgmo, int si, char *equtypetxt)
{ int d_s[]={3,3,12}; printAndReturn(gmoGetEquTypeTxt,2,int ) }

int  GMO_CALLCONV d_gmoGetSolveStatusTxt (gmoHandle_t pgmo, int solvestat, char *sstxt)
{ int d_s[]={3,3,12}; printAndReturn(gmoGetSolveStatusTxt,2,int ) }

int  GMO_CALLCONV d_gmoGetModelStatusTxt (gmoHandle_t pgmo, int modelstat, char *mstxt)
{ int d_s[]={3,3,12}; printAndReturn(gmoGetModelStatusTxt,2,int ) }

int  GMO_CALLCONV d_gmoGetModelTypeTxt (gmoHandle_t pgmo, char *mttxt)
{ int d_s[]={3,12}; printAndReturn(gmoGetModelTypeTxt,1,int ) }

int  GMO_CALLCONV d_gmoGetHeadNTailTxt (gmoHandle_t pgmo, int htrec, char *httxt)
{ int d_s[]={3,3,12}; printAndReturn(gmoGetHeadNTailTxt,2,int ) }

int  GMO_CALLCONV d_gmoDirtyGetRowFNLInstr (gmoHandle_t pgmo, int si, int *len, int opcode[], int field[])
{ int d_s[]={3,3,4,8,8}; printAndReturn(gmoDirtyGetRowFNLInstr,4,int ) }

int  GMO_CALLCONV d_gmoDirtyGetObjFNLInstr (gmoHandle_t pgmo, int *len, int opcode[], int field[])
{ int d_s[]={3,4,8,8}; printAndReturn(gmoDirtyGetObjFNLInstr,3,int ) }

int  GMO_CALLCONV d_gmoDirtySetRowFNLInstr (gmoHandle_t pgmo, int si, int len, const int opcode[], const int field[], void *poolx)
{ int d_s[]={3,3,3,7,7,1}; printAndReturn(gmoDirtySetRowFNLInstr,5,int ) }

int  GMO_CALLCONV d_gmoSetNLObject (gmoHandle_t pgmo, void *NLObj, void *NLPool)
{ int d_s[]={3,1,1}; printAndReturn(gmoSetNLObject,2,int ) }

void  GMO_CALLCONV d_gmoEvalErrorNoMsg (gmoHandle_t pgmo, int noMsg)
{ int d_s[]={0,3}; printNoReturn(gmoEvalErrorNoMsg,1) }

void  GMO_CALLCONV d_gmoEvalErrorNoMsg_MT (gmoHandle_t pgmo, int noMsg, int tidx)
{ int d_s[]={0,3,3}; printNoReturn(gmoEvalErrorNoMsg_MT,2) }

int  GMO_CALLCONV d_gmoEvalNewPoint (gmoHandle_t pgmo, const double X[])
{ int d_s[]={3,5}; printAndReturn(gmoEvalNewPoint,1,int ) }

int  GMO_CALLCONV d_gmoEvalFunc (gmoHandle_t pgmo, int si, const double X[], double *f, int *numErr)
{ int d_s[]={3,3,5,14,4}; printAndReturn(gmoEvalFunc,4,int ) }

int  GMO_CALLCONV d_gmoEvalFunc_MT (gmoHandle_t pgmo, int si, const double X[], double *f, int *numErr, int tidx)
{ int d_s[]={3,3,5,14,4,3}; printAndReturn(gmoEvalFunc_MT,5,int ) }

int  GMO_CALLCONV d_gmoEvalFuncInt (gmoHandle_t pgmo, int si, double *f, int *numErr)
{ int d_s[]={3,3,14,4}; printAndReturn(gmoEvalFuncInt,3,int ) }

int  GMO_CALLCONV d_gmoEvalFuncInt_MT (gmoHandle_t pgmo, int si, double *f, int *numErr, int tidx)
{ int d_s[]={3,3,14,4,3}; printAndReturn(gmoEvalFuncInt_MT,4,int ) }

int  GMO_CALLCONV d_gmoEvalFuncNL (gmoHandle_t pgmo, int si, const double X[], double *fnl, int *numErr)
{ int d_s[]={3,3,5,14,4}; printAndReturn(gmoEvalFuncNL,4,int ) }

int  GMO_CALLCONV d_gmoEvalFuncNL_MT (gmoHandle_t pgmo, int si, const double X[], double *fnl, int *numErr, int tidx)
{ int d_s[]={3,3,5,14,4,3}; printAndReturn(gmoEvalFuncNL_MT,5,int ) }

int  GMO_CALLCONV d_gmoEvalFuncObj (gmoHandle_t pgmo, const double X[], double *f, int *numErr)
{ int d_s[]={3,5,14,4}; printAndReturn(gmoEvalFuncObj,3,int ) }

int  GMO_CALLCONV d_gmoEvalFuncNLObj (gmoHandle_t pgmo, const double X[], double *fnl, int *numErr)
{ int d_s[]={3,5,14,4}; printAndReturn(gmoEvalFuncNLObj,3,int ) }

int  GMO_CALLCONV d_gmoEvalGrad (gmoHandle_t pgmo, int si, const double X[], double *f, double g[], double *gx, int *numErr)
{ int d_s[]={3,3,5,14,6,14,4}; printAndReturn(gmoEvalGrad,6,int ) }

int  GMO_CALLCONV d_gmoEvalGrad_MT (gmoHandle_t pgmo, int si, const double X[], double *f, double g[], double *gx, int *numErr, int tidx)
{ int d_s[]={3,3,5,14,6,14,4,3}; printAndReturn(gmoEvalGrad_MT,7,int ) }

int  GMO_CALLCONV d_gmoEvalGradNL (gmoHandle_t pgmo, int si, const double X[], double *fnl, double g[], double *gxnl, int *numErr)
{ int d_s[]={3,3,5,14,6,14,4}; printAndReturn(gmoEvalGradNL,6,int ) }

int  GMO_CALLCONV d_gmoEvalGradNL_MT (gmoHandle_t pgmo, int si, const double X[], double *fnl, double g[], double *gxnl, int *numErr, int tidx)
{ int d_s[]={3,3,5,14,6,14,4,3}; printAndReturn(gmoEvalGradNL_MT,7,int ) }

int  GMO_CALLCONV d_gmoEvalGradObj (gmoHandle_t pgmo, const double X[], double *f, double g[], double *gx, int *numErr)
{ int d_s[]={3,5,14,6,14,4}; printAndReturn(gmoEvalGradObj,5,int ) }

int  GMO_CALLCONV d_gmoEvalGradNLObj (gmoHandle_t pgmo, const double X[], double *fnl, double g[], double *gxnl, int *numErr)
{ int d_s[]={3,5,14,6,14,4}; printAndReturn(gmoEvalGradNLObj,5,int ) }

int  GMO_CALLCONV d_gmoEvalFuncInterval (gmoHandle_t pgmo, int si, const double Xmin[], const double Xmax[], double *fmin, double *fmax, int *numErr)
{ int d_s[]={3,3,5,5,14,14,4}; printAndReturn(gmoEvalFuncInterval,6,int ) }

int  GMO_CALLCONV d_gmoEvalFuncInterval_MT (gmoHandle_t pgmo, int si, const double Xmin[], const double Xmax[], double *fmin, double *fmax, int *numErr, int tidx)
{ int d_s[]={3,3,5,5,14,14,4,3}; printAndReturn(gmoEvalFuncInterval_MT,7,int ) }

int  GMO_CALLCONV d_gmoEvalGradInterval (gmoHandle_t pgmo, int si, const double Xmin[], const double Xmax[], double *fmin, double *fmax, double Gmin[], double Gmax[], int *numErr)
{ int d_s[]={3,3,5,5,14,14,6,6,4}; printAndReturn(gmoEvalGradInterval,8,int ) }

int  GMO_CALLCONV d_gmoEvalGradInterval_MT (gmoHandle_t pgmo, int si, const double Xmin[], const double Xmax[], double *fmin, double *fmax, double Gmin[], double Gmax[], int *numErr, int tidx)
{ int d_s[]={3,3,5,5,14,14,6,6,4,3}; printAndReturn(gmoEvalGradInterval_MT,9,int ) }

int  GMO_CALLCONV d_gmoEvalGradNLUpdate (gmoHandle_t pgmo, double rhsdelta[], int storejacupd, int *numErr)
{ int d_s[]={3,6,3,4}; printAndReturn(gmoEvalGradNLUpdate,3,int ) }

int  GMO_CALLCONV d_gmoGetJacUpdate (gmoHandle_t pgmo, int ivec[], int jvec[], double JacValue[], int *nrjacupd)
{ int d_s[]={3,8,8,6,21}; printAndReturn(gmoGetJacUpdate,4,int ) }

void  GMO_CALLCONV d_gmoSetExtFuncs (gmoHandle_t pgmo, void *ExtFunMgr)
{ int d_s[]={0,1}; printNoReturn(gmoSetExtFuncs,1) }

int  GMO_CALLCONV d_gmoHessLoad (gmoHandle_t pgmo, int maxJacMult, int *do2dir, int *doHess)
{ int d_s[]={3,3,21,21}; printAndReturn(gmoHessLoad,3,int ) }

int  GMO_CALLCONV d_gmoHessUnload (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoHessUnload,0,int ) }

int  GMO_CALLCONV d_gmoHessDim (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoHessDim,1,int ) }

int  GMO_CALLCONV d_gmoHessNz (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoHessNz,1,int ) }

int  GMO_CALLCONV d_gmoHessStruct (gmoHandle_t pgmo, int si, int HRindex[], int HCindex[], int *HessDim, int *HessNz)
{ int d_s[]={3,3,8,8,4,4}; printAndReturn(gmoHessStruct,5,int ) }

int  GMO_CALLCONV d_gmoHessValue (gmoHandle_t pgmo, int si, int HRindex[], int HCindex[], int *HessDim, int *HessNz, const double Xval[], double Hval[], int *numErr)
{ int d_s[]={3,3,8,8,4,4,5,6,4}; printAndReturn(gmoHessValue,8,int ) }

int  GMO_CALLCONV d_gmoHessVec (gmoHandle_t pgmo, int si, const double X[], const double dx[], double Wdx[], int *numErr)
{ int d_s[]={3,3,5,5,6,4}; printAndReturn(gmoHessVec,5,int ) }

int  GMO_CALLCONV d_gmoHessLagStruct (gmoHandle_t pgmo, int WRindex[], int WCindex[])
{ int d_s[]={3,8,8}; printAndReturn(gmoHessLagStruct,2,int ) }

int  GMO_CALLCONV d_gmoHessLagValue (gmoHandle_t pgmo, const double X[], const double u[], double w[], double objWeight, double conWeight, int *numErr)
{ int d_s[]={3,5,5,6,13,13,4}; printAndReturn(gmoHessLagValue,6,int ) }

int  GMO_CALLCONV d_gmoHessLagVec (gmoHandle_t pgmo, const double X[], const double u[], const double dx[], double Wdx[], double objWeight, double conWeight, int *numErr)
{ int d_s[]={3,5,5,5,6,13,13,4}; printAndReturn(gmoHessLagVec,7,int ) }

int  GMO_CALLCONV d_gmoPrepareAllSolToGDX (gmoHandle_t pgmo, const char *gdxfname, void *scengdx, int dictid)
{ int d_s[]={3,11,1,3}; printAndReturn(gmoPrepareAllSolToGDX,3,int ) }

int  GMO_CALLCONV d_gmoAddSolutionToGDX (gmoHandle_t pgmo, const char *scenuel[])
{ int d_s[]={3,55}; printAndReturn(gmoAddSolutionToGDX,1,int ) }

int  GMO_CALLCONV d_gmoWriteSolDone (gmoHandle_t pgmo, char *msg)
{ int d_s[]={3,12}; printAndReturn(gmoWriteSolDone,1,int ) }

void * GMO_CALLCONV d_gmoViewStore (gmoHandle_t pgmo)
{ int d_s[]={1}; printAndReturn(gmoViewStore,0,void *) }

void  GMO_CALLCONV d_gmoViewRestore (gmoHandle_t pgmo, void **viewptr)
{ int d_s[]={0,2}; printNoReturn(gmoViewRestore,1) }

int  GMO_CALLCONV d_gmoLoadEMPInfo (gmoHandle_t pgmo, const char *empinfofn)
{ int d_s[]={3,11}; printAndReturn(gmoLoadEMPInfo,1,int ) }

int  GMO_CALLCONV d_gmoGetEquVI (gmoHandle_t pgmo, int Mvector[])
{ int d_s[]={3,8}; printAndReturn(gmoGetEquVI,1,int ) }

int  GMO_CALLCONV d_gmoGetEquVIOne (gmoHandle_t pgmo, int si)
{ int d_s[]={3,3}; printAndReturn(gmoGetEquVIOne,1,int ) }

int  GMO_CALLCONV d_gmoGetVarVI (gmoHandle_t pgmo, int Nvector[])
{ int d_s[]={3,8}; printAndReturn(gmoGetVarVI,1,int ) }

int  GMO_CALLCONV d_gmoGetVarVIOne (gmoHandle_t pgmo, int sj)
{ int d_s[]={3,3}; printAndReturn(gmoGetVarVIOne,1,int ) }

int  GMO_CALLCONV d_gmoGetAgentType (gmoHandle_t pgmo, int NumAgentVector[])
{ int d_s[]={3,8}; printAndReturn(gmoGetAgentType,1,int ) }

int  GMO_CALLCONV d_gmoGetAgentTypeOne (gmoHandle_t pgmo, int a)
{ int d_s[]={3,3}; printAndReturn(gmoGetAgentTypeOne,1,int ) }

int  GMO_CALLCONV d_gmoGetBiLevelInfo (gmoHandle_t pgmo, int Nvector[], int Mvector[])
{ int d_s[]={3,8,8}; printAndReturn(gmoGetBiLevelInfo,2,int ) }

char * GMO_CALLCONV d_gmoNameModel (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoNameModel,0,char *) }

void GMO_CALLCONV d_gmoNameModelSet (gmoHandle_t pgmo, const char *x)
{ int d_s[]={0,12}; printNoReturn(gmoNameModelSet,1) }

int  GMO_CALLCONV d_gmoObjNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoObjNZ,0,int ) }

int  GMO_CALLCONV d_gmoObjNLNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoObjNLNZ,0,int ) }

int  GMO_CALLCONV d_gmoObjStyle (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoObjStyle,0,int ) }

void GMO_CALLCONV d_gmoObjStyleSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoObjStyleSet,1) }

int  GMO_CALLCONV d_gmoGetObjOrder (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoGetObjOrder,0,int ) }

int  GMO_CALLCONV d_gmoInterface (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoInterface,0,int ) }

void GMO_CALLCONV d_gmoInterfaceSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoInterfaceSet,1) }

int  GMO_CALLCONV d_gmoIndexBase (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoIndexBase,0,int ) }

void GMO_CALLCONV d_gmoIndexBaseSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoIndexBaseSet,1) }

int  GMO_CALLCONV d_gmoObjReform (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoObjReform,0,int ) }

void GMO_CALLCONV d_gmoObjReformSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoObjReformSet,1) }

int  GMO_CALLCONV d_gmoEmptyOut (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoEmptyOut,0,int ) }

void GMO_CALLCONV d_gmoEmptyOutSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoEmptyOutSet,1) }

double  GMO_CALLCONV d_gmoObjConst (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoObjConst,0,double ) }

double  GMO_CALLCONV d_gmoObjJacVal (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoObjJacVal,0,double ) }

int  GMO_CALLCONV d_gmoModelStat (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoModelStat,0,int ) }

void GMO_CALLCONV d_gmoModelStatSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoModelStatSet,1) }

int  GMO_CALLCONV d_gmoSolveStat (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoSolveStat,0,int ) }

void GMO_CALLCONV d_gmoSolveStatSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoSolveStatSet,1) }

double  GMO_CALLCONV d_gmoPinf (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoPinf,0,double ) }

void GMO_CALLCONV d_gmoPinfSet (gmoHandle_t pgmo, const double x)
{ int d_s[]={0,13}; printNoReturn(gmoPinfSet,1) }

double  GMO_CALLCONV d_gmoMinf (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoMinf,0,double ) }

void GMO_CALLCONV d_gmoMinfSet (gmoHandle_t pgmo, const double x)
{ int d_s[]={0,13}; printNoReturn(gmoMinfSet,1) }

double  GMO_CALLCONV d_gmoInfTol (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoInfTol,0,double ) }

void GMO_CALLCONV d_gmoInfTolSet (gmoHandle_t pgmo, const double x)
{ int d_s[]={0,13}; printNoReturn(gmoInfTolSet,1) }

double  GMO_CALLCONV d_gmoOptTol (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoOptTol,0,double ) }

void GMO_CALLCONV d_gmoOptTolSet (gmoHandle_t pgmo, const double x)
{ int d_s[]={0,13}; printNoReturn(gmoOptTolSet,1) }

int  GMO_CALLCONV d_gmoAltBounds (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoAltBounds,0,int ) }

void GMO_CALLCONV d_gmoAltBoundsSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoAltBoundsSet,1) }

int  GMO_CALLCONV d_gmoAltRHS (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoAltRHS,0,int ) }

void GMO_CALLCONV d_gmoAltRHSSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoAltRHSSet,1) }

int  GMO_CALLCONV d_gmoAltVarTypes (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoAltVarTypes,0,int ) }

void GMO_CALLCONV d_gmoAltVarTypesSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoAltVarTypesSet,1) }

int  GMO_CALLCONV d_gmoForceLinear (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoForceLinear,0,int ) }

void GMO_CALLCONV d_gmoForceLinearSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoForceLinearSet,1) }

int  GMO_CALLCONV d_gmoForceCont (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoForceCont,0,int ) }

void GMO_CALLCONV d_gmoForceContSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoForceContSet,1) }

int  GMO_CALLCONV d_gmoIsQP (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoIsQP,0,int ) }

int  GMO_CALLCONV d_gmoNDisc (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNDisc,0,int ) }

int  GMO_CALLCONV d_gmoMaxQnz (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoMaxQnz,0,int ) }

int  GMO_CALLCONV d_gmoQRows (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoQRows,0,int ) }

int  GMO_CALLCONV d_gmoUseQ (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoUseQ,0,int ) }

void GMO_CALLCONV d_gmoUseQSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoUseQSet,1) }

int  GMO_CALLCONV d_gmoObjQNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoObjQNZ,0,int ) }

int  GMO_CALLCONV d_gmoObjQDiagNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoObjQDiagNZ,0,int ) }

int  GMO_CALLCONV d_gmoNLCodeFun (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNLCodeFun,0,int ) }

void GMO_CALLCONV d_gmoNLCodeFunSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoNLCodeFunSet,1) }

int  GMO_CALLCONV d_gmoMaxSingleFNL (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoMaxSingleFNL,0,int ) }

void * GMO_CALLCONV d_gmoPPool (gmoHandle_t pgmo)
{ int d_s[]={1}; printAndReturn(gmoPPool,0,void *) }

int  GMO_CALLCONV d_gmoNFixed (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNFixed,0,int ) }

int  GMO_CALLCONV d_gmoPermuteCols (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoPermuteCols,0,int ) }

void GMO_CALLCONV d_gmoPermuteColsSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoPermuteColsSet,1) }

int  GMO_CALLCONV d_gmoPermuteRows (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoPermuteRows,0,int ) }

void GMO_CALLCONV d_gmoPermuteRowsSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoPermuteRowsSet,1) }

double  GMO_CALLCONV d_gmoQNaN (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoQNaN,0,double ) }

double  GMO_CALLCONV d_gmoValNA (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoValNA,0,double ) }

int  GMO_CALLCONV d_gmoValNAInt (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoValNAInt,0,int ) }

double  GMO_CALLCONV d_gmoValUndf (gmoHandle_t pgmo)
{ int d_s[]={13}; printAndReturn(gmoValUndf,0,double ) }

int  GMO_CALLCONV d_gmoIgnXCDeriv (gmoHandle_t pgmo)
{ int d_s[]={15}; printAndReturn(gmoIgnXCDeriv,0,int ) }

void GMO_CALLCONV d_gmoIgnXCDerivSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,15}; printNoReturn(gmoIgnXCDerivSet,1) }

int  GMO_CALLCONV d_gmoEvalErrorMethod (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoEvalErrorMethod,0,int ) }

void GMO_CALLCONV d_gmoEvalErrorMethodSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoEvalErrorMethodSet,1) }

int  GMO_CALLCONV d_gmoEvalErrorMaskLevel (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoEvalErrorMaskLevel,0,int ) }

void GMO_CALLCONV d_gmoEvalErrorMaskLevelSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoEvalErrorMaskLevelSet,1) }

int  GMO_CALLCONV d_gmoEvalMaxThreads (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoEvalMaxThreads,0,int ) }

void GMO_CALLCONV d_gmoEvalMaxThreadsSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoEvalMaxThreadsSet,1) }

int  GMO_CALLCONV d_gmoHessMaxDim (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoHessMaxDim,0,int ) }

int  GMO_CALLCONV d_gmoHessMaxNz (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoHessMaxNz,0,int ) }

int  GMO_CALLCONV d_gmoHessLagDim (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoHessLagDim,0,int ) }

int  GMO_CALLCONV d_gmoHessLagNz (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoHessLagNz,0,int ) }

int  GMO_CALLCONV d_gmoHessLagDiagNz (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoHessLagDiagNz,0,int ) }

int  GMO_CALLCONV d_gmoNumVIFunc (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNumVIFunc,0,int ) }

int  GMO_CALLCONV d_gmoNumAgents (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNumAgents,0,int ) }

int  GMO_CALLCONV d_gmoModelType (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoModelType,0,int ) }

void GMO_CALLCONV d_gmoModelTypeSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoModelTypeSet,1) }

int  GMO_CALLCONV d_gmoM (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoM,0,int ) }

int  GMO_CALLCONV d_gmoN (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoN,0,int ) }

int  GMO_CALLCONV d_gmoScaleOpt (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoScaleOpt,0,int ) }

void GMO_CALLCONV d_gmoScaleOptSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoScaleOptSet,1) }

int  GMO_CALLCONV d_gmoSense (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoSense,0,int ) }

void GMO_CALLCONV d_gmoSenseSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoSenseSet,1) }

int  GMO_CALLCONV d_gmoObjVar (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoObjVar,0,int ) }

void GMO_CALLCONV d_gmoObjVarSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoObjVarSet,1) }

int  GMO_CALLCONV d_gmoOptFile (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoOptFile,0,int ) }

void GMO_CALLCONV d_gmoOptFileSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoOptFileSet,1) }

int  GMO_CALLCONV d_gmoPriorOpt (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoPriorOpt,0,int ) }

void GMO_CALLCONV d_gmoPriorOptSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoPriorOptSet,1) }

int  GMO_CALLCONV d_gmoNLConst (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNLConst,0,int ) }

void GMO_CALLCONV d_gmoNLConstSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoNLConstSet,1) }

int  GMO_CALLCONV d_gmoNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNZ,0,int ) }

void GMO_CALLCONV d_gmoNZSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoNZSet,1) }

int  GMO_CALLCONV d_gmoNLNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNLNZ,0,int ) }

int  GMO_CALLCONV d_gmoLNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoLNZ,0,int ) }

int  GMO_CALLCONV d_gmoQNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoQNZ,0,int ) }

int  GMO_CALLCONV d_gmoGNLNZ (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoGNLNZ,0,int ) }

int  GMO_CALLCONV d_gmoNLM (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNLM,0,int ) }

int  GMO_CALLCONV d_gmoNLN (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoNLN,0,int ) }

int  GMO_CALLCONV d_gmoObjRow (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoObjRow,0,int ) }

int  GMO_CALLCONV d_gmoDictionary (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoDictionary,0,int ) }

void GMO_CALLCONV d_gmoDictionarySet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoDictionarySet,1) }

int  GMO_CALLCONV d_gmoHaveBasis (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoHaveBasis,0,int ) }

void GMO_CALLCONV d_gmoHaveBasisSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoHaveBasisSet,1) }

int  GMO_CALLCONV d_gmoModelSeqNr (gmoHandle_t pgmo)
{ int d_s[]={3}; printAndReturn(gmoModelSeqNr,0,int ) }

void GMO_CALLCONV d_gmoModelSeqNrSet (gmoHandle_t pgmo, const int x)
{ int d_s[]={0,3}; printNoReturn(gmoModelSeqNrSet,1) }

char * GMO_CALLCONV d_gmoNameOptFile (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoNameOptFile,0,char *) }

void GMO_CALLCONV d_gmoNameOptFileSet (gmoHandle_t pgmo, const char *x)
{ int d_s[]={0,12}; printNoReturn(gmoNameOptFileSet,1) }

char * GMO_CALLCONV d_gmoNameSolFile (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoNameSolFile,0,char *) }

void GMO_CALLCONV d_gmoNameSolFileSet (gmoHandle_t pgmo, const char *x)
{ int d_s[]={0,12}; printNoReturn(gmoNameSolFileSet,1) }

char * GMO_CALLCONV d_gmoNameXLib (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoNameXLib,0,char *) }

void GMO_CALLCONV d_gmoNameXLibSet (gmoHandle_t pgmo, const char *x)
{ int d_s[]={0,12}; printNoReturn(gmoNameXLibSet,1) }

char * GMO_CALLCONV d_gmoNameMatFile (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoNameMatFile,0,char *) }

void GMO_CALLCONV d_gmoNameMatFileSet (gmoHandle_t pgmo, const char *x)
{ int d_s[]={0,12}; printNoReturn(gmoNameMatFileSet,1) }

char * GMO_CALLCONV d_gmoNameDict (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoNameDict,0,char *) }

void GMO_CALLCONV d_gmoNameDictSet (gmoHandle_t pgmo, const char *x)
{ int d_s[]={0,12}; printNoReturn(gmoNameDictSet,1) }

char * GMO_CALLCONV d_gmoNameInput (gmoHandle_t pgmo, char *buf)
{ int d_s[]={12}; printAndReturn(gmoNameInput,0,char *) }

/* return dirName on success, NULL on failure */
static char *
extractFileDirFileName (const char *fileName, char *dirName, char *fName)
{
  int fileNameLen, shave=0;
  const char *end, *s;
  char *t;

  if (NULL == fileName || NULL == dirName || fName == NULL) {
    return NULL;
  }
  fileNameLen = (int) strlen(fileName);

#if defined(_WIN32)
  /* get the last delimiter */
  for (end = fileName + fileNameLen - 1;
       end >= fileName && '\\' != *end && ':' != *end;  end--);
  /* shave off the trailing delimiter if:
   *  it isn't the first char,
   *  it is a backslash, and
   *  it is not preceded by a delimiter
   */
  if (end > fileName && '\\' == *end
   && (! ('\\' == *(end-1) || ':' == *(end-1)))
     ) {
    end--; shave=1;
  }
#else
  /* non-Windows: implicitly, this is the Unix version */
  /* get the last delimiter */
  for (end = fileName + fileNameLen - 1;
       end >= fileName && '/' != *end;  end--);

  if (end > fileName && '/' == *end) {
    end--; shave=1;
  }
#endif  /* if defined(_WIN32) */

  for (s = fileName, t = dirName;  s <= end;  s++, t++)
    *t = *s;
  *t = '\0';

  if (shave) s++;
  for (t = fName;  s <= fileName + fileNameLen - 1;  s++, t++)
    *t = *s;
  *t = '\0';

  return dirName;
} /* extractFileDirFileName */

static soHandle_t
loadLib (const char *libName, char **errMsg)
{
  soHandle_t h;

#if defined(_WIN32)
  h = LoadLibrary (libName);
  if (NULL == h) {
    *errMsg = winErr;
  }
  else {
    *errMsg = NULL;
  }
#else
  (void) dlerror();
  h = dlopen (libName, RTLD_NOW);
  if (NULL == h) {
    *errMsg = dlerror();
  }
  else {
    *errMsg = NULL;
  }
#endif

  return h;
} /* loadLib */

static int
unLoadLib (soHandle_t hh)
{
  int rc;

#if defined(_WIN32)
  rc = FreeLibrary (hh);
  return ! rc;
#else
  rc = dlclose (hh);
#endif
  return rc;
} /* unLoadLib */

static void *
loadSym (soHandle_t h, const char *sym, char **errMsg)
{
  void *s;
  const char *from;
  char *to;
  const char *tripSym;
  char lcbuf[257];
  char ucbuf[257];
  size_t symLen;
  int trip;

  /* search in this order:
   *  1. lower
   *  2. original
   *  3. upper
   */

  symLen = 0;
  for (trip = 1;  trip <= 3;  trip++) {
    switch (trip) {
    case 1:                             /* lower */
      for (from = sym, to = lcbuf;  *from;  from++, to++) {
        *to = tolower(*from);
      }
      symLen = from - sym;
      lcbuf[symLen] = '\0';
      tripSym = lcbuf;
      break;
    case 2:                             /* original */
      tripSym = sym;
      break;
    case 3:                             /* upper */
      for (from = sym, to = ucbuf;  *from;  from++, to++) {
        *to = toupper(*from);
      }
      ucbuf[symLen] = '\0';
      tripSym = ucbuf;
      break;
    default:
      tripSym = sym;
    } /* end switch */
#if defined(_WIN32)
    s = GetProcAddress (h, tripSym);
    if (NULL != s) {
      return s;
    }
#else
    (void) dlerror();
    s = dlsym (h, tripSym);
    *errMsg = dlerror();
    if (NULL == *errMsg) {
      return s;
    }
#endif
  } /* end loop over symbol name variations */

  return NULL;
} /* loadSym */

/* TNAME = type name, ENAME = exported name */
#define LOADIT(TNAME,ENAME) symName = ENAME; TNAME = (TNAME##_t)(intptr_t) loadSym (h, symName, &errMsg); if (NULL == TNAME) goto symMissing
#define LOADIT_ERR_OK(TNAME,ENAME) symName = ENAME; TNAME = (TNAME##_t)(intptr_t) loadSym (h, symName, &errMsg)

#if ! defined(GMS_DLL_BASENAME)
# define GMS_DLL_BASENAME "joatdclib"
#endif
#if defined(_WIN32)
# if ! defined(GMS_DLL_PREFIX)
#  define GMS_DLL_PREFIX ""
# endif
# if ! defined(GMS_DLL_EXTENSION)
#  define GMS_DLL_EXTENSION ".dll"
# endif
# if ! defined(GMS_DLL_SUFFIX)
#  if defined(_WIN64)
#   define GMS_DLL_SUFFIX "64"
#  else
#   define GMS_DLL_SUFFIX ""
#  endif
# endif

#else  /* start non-Windows */

# if ! defined(GMS_DLL_PREFIX)
#  define GMS_DLL_PREFIX "lib"
# endif
# if ! defined(GMS_DLL_EXTENSION)
#  if defined(__APPLE__)
#   define GMS_DLL_EXTENSION ".dylib"
#  else
#   define GMS_DLL_EXTENSION ".so"
#  endif
# endif
# if ! defined(GMS_DLL_SUFFIX)
#  if defined(__WORDSIZE)
#   if 64 == __WORDSIZE
#    define GMS_DLL_SUFFIX "64"
#   else
#    define GMS_DLL_SUFFIX ""
#   endif
#  elif defined(__SIZEOF_POINTER__)
#   if 4 == __SIZEOF_POINTER__
#    define GMS_DLL_SUFFIX ""
#   elif 8 == __SIZEOF_POINTER__
#    define GMS_DLL_SUFFIX "64"
#   endif
#  elif defined(__sparcv9)
#   define GMS_DLL_SUFFIX "64"
#  elif defined(__sparc)
/*  check __sparc after __sparcv9, both are defined for 64-bit */
#   define GMS_DLL_SUFFIX ""
#  endif
# endif /* ! defined(GMS_DLL_SUFFIX) */
#endif

/* XLibraryLoad: return 0 on success, ~0 on failure */
static int
XLibraryLoad (const char *dllName, char *errBuf, int errBufSize)
{
  char *errMsg;
  char *symName;
  int rc, elen, cl;
  char *ebuf;

  if (isLoaded)
    return 0;
  h = loadLib (dllName, &errMsg);
  if (NULL == h) {
    if (NULL != errBuf) {
      elen = errBufSize;  ebuf = errBuf;
      rc = sprintf (ebuf, "%.*s", elen, "Could not load shared library ");
      elen -= rc;  ebuf+= rc;
      rc = sprintf (ebuf, "%.*s", elen, dllName);
      elen -= rc;  ebuf+= rc;
      rc = sprintf (ebuf, "%.*s", elen, ": ");
      elen -= rc;  ebuf+= rc;
      rc = sprintf (ebuf, "%.*s", elen, errMsg);
      elen -= rc;  ebuf+= rc;
      errBuf[errBufSize-1] = '\0';
    }
    return 1;
  }
  else {
     /* printf ("Loaded shared library %s successfully\n", dllName); */
    if (errBuf && errBufSize)
      errBuf[0] = '\0';
  }

  LOADIT(gmoXCreate, "gmoXCreate");
  LOADIT(gmoXFree, "gmoXFree");
  LOADIT(gmoXCheck, "CgmoXCheck");
  LOADIT(gmoXAPIVersion, "CgmoXAPIVersion");

  if (!gmoXAPIVersion(9,errBuf,&cl))
    return 1;


#define CheckAndLoad(f,nargs,prefix) \
  if (!gmoXCheck(#f,nargs,s,errBuf)) \
    f = &d_##f; \
  else { \
    LOADIT(f,prefix #f); \
  }
  {int s[]={3,12}; CheckAndLoad(gmoLoadDataLegacy,1,"C"); }
  {int s[]={3,3,3}; CheckAndLoad(gmoInitData,2,""); }
  {int s[]={3,11,12}; CheckAndLoad(gmoCompleteData,2,"C"); }
  {int s[]={3,8,8,6}; CheckAndLoad(gmoGetObjQ,3,""); }
  {int s[]={3,3,8,8,6}; CheckAndLoad(gmoGetRowQ,4,""); }
  {int s[]={3,11}; CheckAndLoad(gmoDumpQMakerGDX,1,"C"); }
  {int s[]={3,3,4,4,4,4}; CheckAndLoad(gmoGetColStat,5,""); }
  {int s[]={3,4,4,4}; CheckAndLoad(gmoGetObjStat,3,""); }
  {int s[]={3,3,4,4,4}; CheckAndLoad(gmoGetRowStat,4,""); }
  {int s[]={3,8,8,8,6}; CheckAndLoad(gmoGetMatrixCplex,4,""); }
  {int s[]={3,8,8,6,8}; CheckAndLoad(gmoGetMatrixCol,4,""); }
  {int s[]={3,6,8}; CheckAndLoad(gmoGetObjVector,2,""); }
  {int s[]={3,8,6,8,4,4}; CheckAndLoad(gmoGetObjSparse,5,""); }
  {int s[]={3,3,8,6,8,4,4}; CheckAndLoad(gmoGetRowSparse,6,""); }
  {int s[]={3,3,8,6,8,4,4}; CheckAndLoad(gmoGetColSparse,6,""); }
  {int s[]={3,8,8,6,8}; CheckAndLoad(gmoGetMatrixRow,4,""); }
  {int s[]={0,4,4,4}; CheckAndLoad(gmoGetSosCounts,3,""); }
  {int s[]={3,8,8,8,6}; CheckAndLoad(gmoGetSosConstraints,4,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetVarSosSetOne,1,""); }
  {int s[]={0,3,2,14,4,4}; CheckAndLoad(gmoGetColJacInfoOne,5,""); }
  {int s[]={0,3,2,14,4,4}; CheckAndLoad(gmoGetRowJacInfoOne,5,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetVarL,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetVarLOne,1,""); }
  {int s[]={3,5}; CheckAndLoad(gmoSetVarL,1,""); }
  {int s[]={0,3,13}; CheckAndLoad(gmoSetVarLOne,2,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetVarM,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetVarMOne,1,""); }
  {int s[]={3,5}; CheckAndLoad(gmoSetVarM,1,""); }
  {int s[]={12,3}; CheckAndLoad(gmoGetVarNameOne,1,"C"); }
  {int s[]={12,3,11}; CheckAndLoad(gmoGetVarNameCustomOne,2,"C"); }
  {int s[]={3,6}; CheckAndLoad(gmoGetVarLower,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetVarLowerOne,1,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetVarUpper,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetVarUpperOne,1,""); }
  {int s[]={3,5,5}; CheckAndLoad(gmoSetAltVarBounds,2,""); }
  {int s[]={0,3,13}; CheckAndLoad(gmoSetAltVarLowerOne,2,""); }
  {int s[]={0,3,13}; CheckAndLoad(gmoSetAltVarUpperOne,2,""); }
  {int s[]={3,8}; CheckAndLoad(gmoGetVarType,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetVarTypeOne,1,""); }
  {int s[]={3,7}; CheckAndLoad(gmoSetAltVarType,1,""); }
  {int s[]={0,3,3}; CheckAndLoad(gmoSetAltVarTypeOne,2,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetVarTypeCnt,1,""); }
  {int s[]={0,8}; CheckAndLoad(gmoGetVarStat,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetVarStatOne,1,""); }
  {int s[]={0,8}; CheckAndLoad(gmoSetVarStat,1,""); }
  {int s[]={0,3,3}; CheckAndLoad(gmoSetVarStatOne,2,""); }
  {int s[]={0,8}; CheckAndLoad(gmoGetVarCStat,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetVarCStatOne,1,""); }
  {int s[]={0,8}; CheckAndLoad(gmoSetVarCStat,1,""); }
  {int s[]={15}; CheckAndLoad(gmoBasisIsFull,0,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetVarPrior,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetVarPriorOne,1,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetVarScale,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetVarScaleOne,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetVarStageOne,1,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetEquL,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetEquLOne,1,""); }
  {int s[]={3,5}; CheckAndLoad(gmoSetEquL,1,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetEquM,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetEquMOne,1,""); }
  {int s[]={3,5}; CheckAndLoad(gmoSetEquM,1,""); }
  {int s[]={12,3}; CheckAndLoad(gmoGetEquNameOne,1,"C"); }
  {int s[]={12,3,11}; CheckAndLoad(gmoGetEquNameCustomOne,2,"C"); }
  {int s[]={12}; CheckAndLoad(gmoGetObjName,0,"C"); }
  {int s[]={12,11}; CheckAndLoad(gmoGetObjNameCustom,1,"C"); }
  {int s[]={3,6}; CheckAndLoad(gmoGetRhs,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetRhsOne,1,""); }
  {int s[]={3,5}; CheckAndLoad(gmoSetAltRHS,1,""); }
  {int s[]={0,3,13}; CheckAndLoad(gmoSetAltRHSOne,2,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetEquSlack,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetEquSlackOne,1,""); }
  {int s[]={3,5}; CheckAndLoad(gmoSetEquSlack,1,""); }
  {int s[]={3,8}; CheckAndLoad(gmoGetEquType,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetEquTypeOne,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetEquTypeCnt,1,""); }
  {int s[]={0,8}; CheckAndLoad(gmoGetEquStat,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetEquStatOne,1,""); }
  {int s[]={0,8}; CheckAndLoad(gmoSetEquStat,1,""); }
  {int s[]={0,8}; CheckAndLoad(gmoGetEquCStat,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetEquCStatOne,1,""); }
  {int s[]={0,8}; CheckAndLoad(gmoSetEquCStat,1,""); }
  {int s[]={3,8}; CheckAndLoad(gmoGetEquMatch,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetEquMatchOne,1,""); }
  {int s[]={3,6}; CheckAndLoad(gmoGetEquScale,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetEquScaleOne,1,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetEquStageOne,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetEquOrderOne,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetRowQNZOne,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetRowQDiagNZOne,1,""); }
  {int s[]={0,4,4,4,8}; CheckAndLoad(gmoGetXLibCounts,4,""); }
  {int s[]={13,3}; CheckAndLoad(gmoGetHeadnTail,1,""); }
  {int s[]={0,3,13}; CheckAndLoad(gmoSetHeadnTail,2,""); }
  {int s[]={3,8}; CheckAndLoad(gmoSetEquPermutation,1,""); }
  {int s[]={3,8,3}; CheckAndLoad(gmoSetRvEquPermutation,2,""); }
  {int s[]={3,8}; CheckAndLoad(gmoSetVarPermutation,1,""); }
  {int s[]={3,8,3}; CheckAndLoad(gmoSetRvVarPermutation,2,""); }
  {int s[]={3}; CheckAndLoad(gmoSetNRowPerm,0,""); }
  {int s[]={3,4,4,4,8,8,6}; CheckAndLoad(gmoDirtyExtractDefVar,6,""); }
  {int s[]={3,5,5}; CheckAndLoad(gmoSetSolution2,2,""); }
  {int s[]={3,5,5,5,5}; CheckAndLoad(gmoSetSolution,4,""); }
  {int s[]={3,5,5,5,5,8,8,8,8}; CheckAndLoad(gmoSetSolution8,8,""); }
  {int s[]={3,3,5,5,7,7}; CheckAndLoad(gmoSetSolutionFixer,5,""); }
  {int s[]={3,3,14,14,4,4}; CheckAndLoad(gmoGetSolutionVarRec,5,""); }
  {int s[]={3,3,13,13,3,3}; CheckAndLoad(gmoSetSolutionVarRec,5,""); }
  {int s[]={3,3,14,14,4,4}; CheckAndLoad(gmoGetSolutionEquRec,5,""); }
  {int s[]={3,3,13,13,3,3}; CheckAndLoad(gmoSetSolutionEquRec,5,""); }
  {int s[]={3,8,8,8,8}; CheckAndLoad(gmoSetSolutionStatus,4,""); }
  {int s[]={3}; CheckAndLoad(gmoCompleteSolution,0,""); }
  {int s[]={3}; CheckAndLoad(gmoLoadSolutionLegacy,0,""); }
  {int s[]={3}; CheckAndLoad(gmoUnloadSolutionLegacy,0,""); }
  {int s[]={3,11,15,15,15}; CheckAndLoad(gmoLoadSolutionGDX,4,"C"); }
  {int s[]={3,11,15,15,15}; CheckAndLoad(gmoUnloadSolutionGDX,4,"C"); }
  {int s[]={3,12}; CheckAndLoad(gmoLastError,1,"C"); }
  {int s[]={0}; CheckAndLoad(gmoClearError,0,""); }
  {int s[]={13}; CheckAndLoad(gmoMemUsed,0,""); }
  {int s[]={13}; CheckAndLoad(gmoPeakMemUsed,0,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetiSolver,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetjSolver,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetiModel,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetjModel,1,""); }
  {int s[]={3,3,3,13,13,13,13,3,3,7,5,7}; CheckAndLoad(gmoAddRow,11,""); }
  {int s[]={3,3,13,13,13,13,3,3,13,13,3,7,5,7}; CheckAndLoad(gmoAddCol,13,""); }
  {int s[]={0}; CheckAndLoad(gmoCompleteJacs,0,""); }
  {int s[]={3}; CheckAndLoad(gmoCrudeness,0,""); }
  {int s[]={1}; CheckAndLoad(gmoDict,0,""); }
  {int s[]={0,1}; CheckAndLoad(gmoSetDictObject,1,""); }
  {int s[]={1}; CheckAndLoad(gmoEnvironment,0,""); }
  {int s[]={3,1,12}; CheckAndLoad(gmoRegisterEnvironment,2,"C"); }
  {int s[]={3,3,12}; CheckAndLoad(gmoGetVarTypeTxt,2,"C"); }
  {int s[]={3,3,12}; CheckAndLoad(gmoGetEquTypeTxt,2,"C"); }
  {int s[]={3,3,12}; CheckAndLoad(gmoGetSolveStatusTxt,2,"C"); }
  {int s[]={3,3,12}; CheckAndLoad(gmoGetModelStatusTxt,2,"C"); }
  {int s[]={3,12}; CheckAndLoad(gmoGetModelTypeTxt,1,"C"); }
  {int s[]={3,3,12}; CheckAndLoad(gmoGetHeadNTailTxt,2,"C"); }
  {int s[]={3,3,4,8,8}; CheckAndLoad(gmoDirtyGetRowFNLInstr,4,""); }
  {int s[]={3,4,8,8}; CheckAndLoad(gmoDirtyGetObjFNLInstr,3,""); }
  {int s[]={3,3,3,7,7,1}; CheckAndLoad(gmoDirtySetRowFNLInstr,5,""); }
  {int s[]={3,1,1}; CheckAndLoad(gmoSetNLObject,2,""); }
  {int s[]={0,3}; CheckAndLoad(gmoEvalErrorNoMsg,1,""); }
  {int s[]={0,3,3}; CheckAndLoad(gmoEvalErrorNoMsg_MT,2,""); }
  {int s[]={3,5}; CheckAndLoad(gmoEvalNewPoint,1,""); }
  {int s[]={3,3,5,14,4}; CheckAndLoad(gmoEvalFunc,4,""); }
  {int s[]={3,3,5,14,4,3}; CheckAndLoad(gmoEvalFunc_MT,5,""); }
  {int s[]={3,3,14,4}; CheckAndLoad(gmoEvalFuncInt,3,""); }
  {int s[]={3,3,14,4,3}; CheckAndLoad(gmoEvalFuncInt_MT,4,""); }
  {int s[]={3,3,5,14,4}; CheckAndLoad(gmoEvalFuncNL,4,""); }
  {int s[]={3,3,5,14,4,3}; CheckAndLoad(gmoEvalFuncNL_MT,5,""); }
  {int s[]={3,5,14,4}; CheckAndLoad(gmoEvalFuncObj,3,""); }
  {int s[]={3,5,14,4}; CheckAndLoad(gmoEvalFuncNLObj,3,""); }
  {int s[]={3,3,5,14,6,14,4}; CheckAndLoad(gmoEvalGrad,6,""); }
  {int s[]={3,3,5,14,6,14,4,3}; CheckAndLoad(gmoEvalGrad_MT,7,""); }
  {int s[]={3,3,5,14,6,14,4}; CheckAndLoad(gmoEvalGradNL,6,""); }
  {int s[]={3,3,5,14,6,14,4,3}; CheckAndLoad(gmoEvalGradNL_MT,7,""); }
  {int s[]={3,5,14,6,14,4}; CheckAndLoad(gmoEvalGradObj,5,""); }
  {int s[]={3,5,14,6,14,4}; CheckAndLoad(gmoEvalGradNLObj,5,""); }
  {int s[]={3,3,5,5,14,14,4}; CheckAndLoad(gmoEvalFuncInterval,6,""); }
  {int s[]={3,3,5,5,14,14,4,3}; CheckAndLoad(gmoEvalFuncInterval_MT,7,""); }
  {int s[]={3,3,5,5,14,14,6,6,4}; CheckAndLoad(gmoEvalGradInterval,8,""); }
  {int s[]={3,3,5,5,14,14,6,6,4,3}; CheckAndLoad(gmoEvalGradInterval_MT,9,""); }
  {int s[]={3,6,3,4}; CheckAndLoad(gmoEvalGradNLUpdate,3,""); }
  {int s[]={3,8,8,6,21}; CheckAndLoad(gmoGetJacUpdate,4,""); }
  {int s[]={0,1}; CheckAndLoad(gmoSetExtFuncs,1,""); }
  {int s[]={3,3,21,21}; CheckAndLoad(gmoHessLoad,3,""); }
  {int s[]={3}; CheckAndLoad(gmoHessUnload,0,""); }
  {int s[]={3,3}; CheckAndLoad(gmoHessDim,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoHessNz,1,""); }
  {int s[]={3,3,8,8,4,4}; CheckAndLoad(gmoHessStruct,5,""); }
  {int s[]={3,3,8,8,4,4,5,6,4}; CheckAndLoad(gmoHessValue,8,""); }
  {int s[]={3,3,5,5,6,4}; CheckAndLoad(gmoHessVec,5,""); }
  {int s[]={3,8,8}; CheckAndLoad(gmoHessLagStruct,2,""); }
  {int s[]={3,5,5,6,13,13,4}; CheckAndLoad(gmoHessLagValue,6,""); }
  {int s[]={3,5,5,5,6,13,13,4}; CheckAndLoad(gmoHessLagVec,7,""); }
  {int s[]={3,11,1,3}; CheckAndLoad(gmoPrepareAllSolToGDX,3,"C"); }
  {int s[]={3,55}; CheckAndLoad(gmoAddSolutionToGDX,1,"C"); }
  {int s[]={3,12}; CheckAndLoad(gmoWriteSolDone,1,"C"); }
  {int s[]={1}; CheckAndLoad(gmoViewStore,0,""); }
  {int s[]={0,2}; CheckAndLoad(gmoViewRestore,1,""); }
  {int s[]={3,11}; CheckAndLoad(gmoLoadEMPInfo,1,"C"); }
  {int s[]={3,8}; CheckAndLoad(gmoGetEquVI,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetEquVIOne,1,""); }
  {int s[]={3,8}; CheckAndLoad(gmoGetVarVI,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetVarVIOne,1,""); }
  {int s[]={3,8}; CheckAndLoad(gmoGetAgentType,1,""); }
  {int s[]={3,3}; CheckAndLoad(gmoGetAgentTypeOne,1,""); }
  {int s[]={3,8,8}; CheckAndLoad(gmoGetBiLevelInfo,2,""); }
  {int s[]={12}; CheckAndLoad(gmoNameModel,0,"C"); }
  {int s[]={0,12}; CheckAndLoad(gmoNameModelSet,1,"C"); }
  {int s[]={3}; CheckAndLoad(gmoObjNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoObjNLNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoObjStyle,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoObjStyleSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoGetObjOrder,0,""); }
  {int s[]={3}; CheckAndLoad(gmoInterface,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoInterfaceSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoIndexBase,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoIndexBaseSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoObjReform,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoObjReformSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoEmptyOut,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoEmptyOutSet,1,""); }
  {int s[]={13}; CheckAndLoad(gmoObjConst,0,""); }
  {int s[]={13}; CheckAndLoad(gmoObjJacVal,0,""); }
  {int s[]={3}; CheckAndLoad(gmoModelStat,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoModelStatSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoSolveStat,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoSolveStatSet,1,""); }
  {int s[]={13}; CheckAndLoad(gmoPinf,0,""); }
  {int s[]={0,13}; CheckAndLoad(gmoPinfSet,1,""); }
  {int s[]={13}; CheckAndLoad(gmoMinf,0,""); }
  {int s[]={0,13}; CheckAndLoad(gmoMinfSet,1,""); }
  {int s[]={13}; CheckAndLoad(gmoInfTol,0,""); }
  {int s[]={0,13}; CheckAndLoad(gmoInfTolSet,1,""); }
  {int s[]={13}; CheckAndLoad(gmoOptTol,0,""); }
  {int s[]={0,13}; CheckAndLoad(gmoOptTolSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoAltBounds,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoAltBoundsSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoAltRHS,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoAltRHSSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoAltVarTypes,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoAltVarTypesSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoForceLinear,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoForceLinearSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoForceCont,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoForceContSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoIsQP,0,""); }
  {int s[]={3}; CheckAndLoad(gmoNDisc,0,""); }
  {int s[]={3}; CheckAndLoad(gmoMaxQnz,0,""); }
  {int s[]={3}; CheckAndLoad(gmoQRows,0,""); }
  {int s[]={15}; CheckAndLoad(gmoUseQ,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoUseQSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoObjQNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoObjQDiagNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoNLCodeFun,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoNLCodeFunSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoMaxSingleFNL,0,""); }
  {int s[]={1}; CheckAndLoad(gmoPPool,0,""); }
  {int s[]={3}; CheckAndLoad(gmoNFixed,0,""); }
  {int s[]={15}; CheckAndLoad(gmoPermuteCols,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoPermuteColsSet,1,""); }
  {int s[]={15}; CheckAndLoad(gmoPermuteRows,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoPermuteRowsSet,1,""); }
  {int s[]={13}; CheckAndLoad(gmoQNaN,0,""); }
  {int s[]={13}; CheckAndLoad(gmoValNA,0,""); }
  {int s[]={3}; CheckAndLoad(gmoValNAInt,0,""); }
  {int s[]={13}; CheckAndLoad(gmoValUndf,0,""); }
  {int s[]={15}; CheckAndLoad(gmoIgnXCDeriv,0,""); }
  {int s[]={0,15}; CheckAndLoad(gmoIgnXCDerivSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoEvalErrorMethod,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoEvalErrorMethodSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoEvalErrorMaskLevel,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoEvalErrorMaskLevelSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoEvalMaxThreads,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoEvalMaxThreadsSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoHessMaxDim,0,""); }
  {int s[]={3}; CheckAndLoad(gmoHessMaxNz,0,""); }
  {int s[]={3}; CheckAndLoad(gmoHessLagDim,0,""); }
  {int s[]={3}; CheckAndLoad(gmoHessLagNz,0,""); }
  {int s[]={3}; CheckAndLoad(gmoHessLagDiagNz,0,""); }
  {int s[]={3}; CheckAndLoad(gmoNumVIFunc,0,""); }
  {int s[]={3}; CheckAndLoad(gmoNumAgents,0,""); }
  {int s[]={3}; CheckAndLoad(gmoModelType,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoModelTypeSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoM,0,""); }
  {int s[]={3}; CheckAndLoad(gmoN,0,""); }
  {int s[]={3}; CheckAndLoad(gmoScaleOpt,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoScaleOptSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoSense,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoSenseSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoObjVar,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoObjVarSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoOptFile,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoOptFileSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoPriorOpt,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoPriorOptSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoNLConst,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoNLConstSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoNZ,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoNZSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoNLNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoLNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoQNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoGNLNZ,0,""); }
  {int s[]={3}; CheckAndLoad(gmoNLM,0,""); }
  {int s[]={3}; CheckAndLoad(gmoNLN,0,""); }
  {int s[]={3}; CheckAndLoad(gmoObjRow,0,""); }
  {int s[]={3}; CheckAndLoad(gmoDictionary,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoDictionarySet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoHaveBasis,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoHaveBasisSet,1,""); }
  {int s[]={3}; CheckAndLoad(gmoModelSeqNr,0,""); }
  {int s[]={0,3}; CheckAndLoad(gmoModelSeqNrSet,1,""); }
  {int s[]={12}; CheckAndLoad(gmoNameOptFile,0,"C"); }
  {int s[]={0,12}; CheckAndLoad(gmoNameOptFileSet,1,"C"); }
  {int s[]={12}; CheckAndLoad(gmoNameSolFile,0,"C"); }
  {int s[]={0,12}; CheckAndLoad(gmoNameSolFileSet,1,"C"); }
  {int s[]={12}; CheckAndLoad(gmoNameXLib,0,"C"); }
  {int s[]={0,12}; CheckAndLoad(gmoNameXLibSet,1,"C"); }
  {int s[]={12}; CheckAndLoad(gmoNameMatFile,0,"C"); }
  {int s[]={0,12}; CheckAndLoad(gmoNameMatFileSet,1,"C"); }
  {int s[]={12}; CheckAndLoad(gmoNameDict,0,"C"); }
  {int s[]={0,12}; CheckAndLoad(gmoNameDictSet,1,"C"); }
  {int s[]={12}; CheckAndLoad(gmoNameInput,0,"C"); }

 return 0;

 symMissing:
  if (errBuf && errBufSize>0) {
    elen = errBufSize;  ebuf = errBuf;
    rc = sprintf (ebuf, "%.*s", elen, "Could not load symbol '");
    elen -= rc;  ebuf+= rc;
    rc = sprintf (ebuf, "%.*s", elen, symName);
    elen -= rc;  ebuf+= rc;
    rc = sprintf (ebuf, "%.*s", elen, "': ");
    elen -= rc;  ebuf+= rc;
    rc = sprintf (ebuf, "%.*s", elen, errMsg);
    elen -= rc;  ebuf+= rc;
    errBuf[errBufSize-1] = '\0';
    /* printf ("%s\n", errBuf); */
    return 2;
  }

 return 0;

} /* XLibraryLoad */

static int
libloader(const char *dllPath, const char *dllName, char *msgBuf, int msgBufSize)
{

  char dllNameBuf[512];
  int myrc = 0;
  char gms_dll_suffix[4];

#if ! defined(GMS_DLL_PREFIX)
# error "GMS_DLL_PREFIX expected but not defined"
#endif
#if ! defined(GMS_DLL_BASENAME)
# error "GMS_DLL_BASENAME expected but not defined"
#endif
#if ! defined(GMS_DLL_EXTENSION)
# error "GMS_DLL_EXTENSION expected but not defined"
#endif
#if ! defined(GMS_DLL_SUFFIX)
# if defined (_WIN32)
#   error "GMS_DLL_SUFFIX expected but not defined"
# else
  struct utsname uts;

  myrc = uname(&uts);
  if (myrc)
  {
    strcpy(msgBuf,"Error, cannot define library name suffix");
    return 0;
  }
  if (0==strcmp(uts.sysname,"AIX")) /* assume AIX is 64-bit */
    strcpy (gms_dll_suffix, "64");
  else
  {
    strcpy(msgBuf,"Error, cannot define library name suffix");
    return 0;
  }
# endif
#else
  strcpy (gms_dll_suffix, GMS_DLL_SUFFIX);
#endif


  if (NULL != msgBuf) msgBuf[0] = '\0';

  if (! isLoaded) {
    if (NULL != dllPath && '\0' != *dllPath) {
      strncpy(dllNameBuf, dllPath, sizeof(dllNameBuf)-1);
      dllNameBuf[sizeof(dllNameBuf)-2] = '\0';
#if defined(_WIN32)
      if ('\\' != dllNameBuf[strlen(dllNameBuf)])
        strcat(dllNameBuf,"\\");
#else
      if ('/' != dllNameBuf[strlen(dllNameBuf)])
        strcat(dllNameBuf,"/");
#endif
    }
    else {
      dllNameBuf[0] = '\0';
    }
    if (NULL != dllName && '\0' != *dllName) {
      strncat(dllNameBuf, dllName, sizeof(dllNameBuf)-strlen(dllNameBuf));
      dllNameBuf[sizeof(dllNameBuf)-1] = '\0';
    }
    else {
      strncat(dllNameBuf, GMS_DLL_PREFIX GMS_DLL_BASENAME, sizeof(dllNameBuf)-strlen(dllNameBuf));
      strncat(dllNameBuf, gms_dll_suffix                 , sizeof(dllNameBuf)-strlen(dllNameBuf));
      strncat(dllNameBuf, GMS_DLL_EXTENSION              , sizeof(dllNameBuf)-strlen(dllNameBuf));
    }
    isLoaded = ! XLibraryLoad (dllNameBuf, msgBuf, msgBufSize);
    if (isLoaded) {
    }
    else {                              /* library load failed */
      myrc |= 1;
    }
  }
  return (myrc & 1) == 0;
}


/* gmoGetReady: return false on failure to load library, true on success */
int gmoGetReady (char *msgBuf, int msgBufSize)
{
  return libloader(NULL, NULL, msgBuf, msgBufSize);
} /* gmoGetReady */

/* gmoGetReadyD: return false on failure to load library, true on success */
int gmoGetReadyD (const char *dirName, char *msgBuf, int msgBufSize)
{
  return libloader(dirName, NULL, msgBuf, msgBufSize);
} /* gmoGetReadyD */

/* gmoGetReadyL: return false on failure to load library, true on success */
int gmoGetReadyL (const char *libName, char *msgBuf, int msgBufSize)
{
  char dirName[1024],fName[1024];
  extractFileDirFileName (libName, dirName, fName);
  return libloader(dirName, fName, msgBuf, msgBufSize);
} /* gmoGetReadyL */

/* gmoCreate: return false on failure to load library, true on success */
int gmoCreate (gmoHandle_t *pgmo, char *msgBuf, int msgBufSize)
{
  int gmoIsReady;

  gmoIsReady = gmoGetReady (msgBuf, msgBufSize);
  if (! gmoIsReady) {
    return 0;
  }
  assert(gmoXCreate);
  gmoXCreate(pgmo);
  if(pgmo == NULL)
  { strcpy(msgBuf,"Error while creating object"); return 0; }
  objectCount++;
  return 1;                     /* return true on successful library load */
} /* gmoCreate */

/* gmoCreateD: return false on failure to load library, true on success */
int gmoCreateD (gmoHandle_t *pgmo, const char *dirName,
                char *msgBuf, int msgBufSize)
{
  int gmoIsReady;

  gmoIsReady = gmoGetReadyD (dirName, msgBuf, msgBufSize);
  if (! gmoIsReady) {
    return 0;
  }
  assert(gmoXCreate);
  gmoXCreate(pgmo);
  if(pgmo == NULL)
  { strcpy(msgBuf,"Error while creating object"); return 0; }
  objectCount++;
  return 1;                     /* return true on successful library load */
} /* gmoCreateD */

/* gmoCreateL: return false on failure to load library, true on success */
int gmoCreateL (gmoHandle_t *pgmo, const char *libName,
                char *msgBuf, int msgBufSize)
{
  int gmoIsReady;

  gmoIsReady = gmoGetReadyL (libName, msgBuf, msgBufSize);
  if (! gmoIsReady) {
    return 0;
  }
  assert(gmoXCreate);
  gmoXCreate(pgmo);
  if(pgmo == NULL)
  { strcpy(msgBuf,"Error while creating object"); return 0; }
  objectCount++;
  return 1;                     /* return true on successful library load */
} /* gmoCreateL */

int gmoFree   (gmoHandle_t *pgmo)
{
  assert(gmoXFree);
  gmoXFree(pgmo); pgmo = NULL;
  objectCount--;
  return 1;
} /* gmoFree */

int gmoLibraryLoaded(void)
{
  return isLoaded;
} /* gmoLibraryLoaded */

int gmoLibraryUnload(void)
{
  if (objectCount > 0)
    return 0;
  isLoaded = 0;
  (void) unLoadLib(h);
  return 1;
} /* gmoLibraryUnload */

int gmoGetScreenIndicator(void)
{
  return ScreenIndicator;
}

void gmoSetScreenIndicator(int scrind)
{
  ScreenIndicator = scrind ? 1 : 0;
}

int gmoGetExceptionIndicator(void)
{
   return ExceptionIndicator;
}

void gmoSetExceptionIndicator(int excind)
{
  ExceptionIndicator = excind ? 1 : 0;
}

int gmoGetExitIndicator(void)
{
  return ExitIndicator;
}

void gmoSetExitIndicator(int extind)
{
  ExitIndicator = extind ? 1 : 0;
}

gmoErrorCallback_t gmoGetErrorCallback(void)
{
  return ErrorCallBack;
}

void gmoSetErrorCallback(gmoErrorCallback_t func)
{
  ErrorCallBack = func;
}

int gmoGetAPIErrorCount(void)
{
  return APIErrorCount;
}

void gmoSetAPIErrorCount(int ecnt)
{
  APIErrorCount = ecnt;
}

void gmoErrorHandling(const char *msg)
{
  APIErrorCount++;
  if (ScreenIndicator) { printf("%s\n", msg); fflush(stdout); }
  if (ErrorCallBack)
     if (ErrorCallBack(APIErrorCount, msg)) exit(123);
  assert(!ExceptionIndicator);
  if (ExitIndicator) exit(123);
}

