/* Copyright (C) GAMS Development 2010
   All Rights Reserved.
   This code is published under the Common Public License.
  
   $Id: gdxcc.h 783 2009-10-23 09:26:06Z stefan $

   Author:  Lutz Westermann
*/

/* gmomcc.h
 * Header file for C-style interface to the GMO library
 * generated by apiwrapper
 */

#if ! defined(_GMOCC_H_)
#     define  _GMOCC_H_

#define GMOAPIVERSION 8


enum gmoEquType {
  equ_E = 0,
  equ_G = 1,
  equ_L = 2,
  equ_N = 3,
  equ_X = 4,
  equ_C = 5  };

enum gmoVarType {
  var_X  = 0,
  var_B  = 1,
  var_I  = 2,
  var_S1 = 3,
  var_S2 = 4,
  var_SC = 5,
  var_SI = 6  };

enum gmoEquOrder {
  order_ERR = 0,
  order_L   = 1,
  order_Q   = 2,
  order_NL  = 3  };

enum gmoVarFreeType {
  var_X_F = 0,
  var_X_N = 1,
  var_X_P = 2  };

enum gmoBasisStatus {
  Bstat_Lower = 0,
  Bstat_Upper = 1,
  Bstat_Basic = 2,
  Bstat_Super = 3  };

enum gmoVarEquStatus {
  Cstat_OK     = 0,
  Cstat_NonOpt = 1,
  Cstat_Infeas = 2,
  Cstat_UnBnd  = 3  };

enum gmoObjectiveType {
  ObjType_Var = 0,
  ObjType_Equ = 1,
  ObjType_Fun = 2  };

enum gmoInterfaceType {
  IFace_Processed = 0,
  IFace_Raw       = 1  };

enum gmoObjectiveSense {
  Obj_Min = 0,
  Obj_Max = 1  };

enum gmoSolverStatus {
  SolveStat_Normal      = 1,
  SolveStat_Iteration   = 2,
  SolveStat_Resource    = 3,
  SolveStat_Solver      = 4,
  SolveStat_EvalError   = 5,
  SolveStat_Capability  = 6,
  SolveStat_License     = 7,
  SolveStat_User        = 8,
  SolveStat_SetupErr    = 9,
  SolveStat_SolverErr   = 10,
  SolveStat_InternalErr = 11,
  SolveStat_Skipped     = 12,
  SolveStat_SystemErr   = 13  };

enum gmoModelStatus {
  ModelStat_OptimalGlobal        = 1,
  ModelStat_OptimalLocal         = 2,
  ModelStat_Unbounded            = 3,
  ModelStat_InfeasibleGlobal     = 4,
  ModelStat_InfeasibleLocal      = 5,
  ModelStat_InfeasibleIntermed   = 6,
  ModelStat_NonOptimalIntermed   = 7,
  ModelStat_Integer              = 8,
  ModelStat_NonIntegerIntermed   = 9,
  ModelStat_IntegerInfeasible    = 10,
  ModelStat_LicenseError         = 11,
  ModelStat_ErrorUnknown         = 12,
  ModelStat_ErrorNoSolution      = 13,
  ModelStat_NoSolutionReturned   = 14,
  ModelStat_SolvedUnique         = 15,
  ModelStat_Solved               = 16,
  ModelStat_SolvedSingular       = 17,
  ModelStat_UnboundedNoSolution  = 18,
  ModelStat_InfeasibleNoSolution = 19  };

enum gmoHeadnTail {
  Hiterused  = 3,
  Hresused   = 4,
  Hobjval    = 5,
  Hdomused   = 6,
  Hsolution  = 9,
  Tmipnod    = 10,
  Tninf      = 11,
  Tnopt      = 12,
  Tmipbest   = 14,
  Trescalc   = 15,
  Tresderiv  = 16,
  Tresin     = 17,
  Tresout    = 18,
  Tsinf      = 19,
  Tforcesave = 20,
  Trobj      = 21  };

enum gmoHTcard {
  numheader = 9,
  numtail   = 12  };

enum gmoEvalRC {
  EvalRCOK     = 0,
  EvalRCFUNC   = 1,
  EvalRCGRAD   = 2,
  EvalRCHESS   = 3,
  EvalRCSYSTEM = 4  };

enum gmoProcType {
  Proc_none           = 0,
  Proc_lp             = 1,
  Proc_mip            = 2,
  Proc_rmip           = 3,
  Proc_nlp            = 4,
  Proc_mcp            = 5,
  Proc_mpec           = 6,
  Proc_rmpec          = 7,
  Proc_cns            = 8,
  Proc_dnlp           = 9,
  Proc_rminlp         = 10,
  Proc_minlp          = 11,
  Proc_qcp            = 12,
  Proc_miqcp          = 13,
  Proc_rmiqcp         = 14,
  Proc_emp            = 15,
  Proc_nrofmodeltypes = 16  };

enum gmoEMPAgentType {
  MinAgent = 0,
  MaxAgent = 1,
  VIAgent  = 2  };

enum gmoErrorMethodNum {
  ERRORMETHOD_KEEPGOING = 0,
  ERRORMETHOD_FASTSTOP  = 1  };


#if defined(_WIN32)
# define GMO_CALLCONV __stdcall
#else
# define GMO_CALLCONV
#endif

#if defined(__cplusplus)
extern "C" {
#endif

struct gmoRec;
typedef struct gmoRec *gmoHandle_t;

typedef int (*gmoErrorCallback_t) (int ErrCount, const char *msg);

/* headers for "wrapper" routines implemented in C */
int gmoGetReady  (char *msgBuf, int msgBufLen);
int gmoGetReadyD (const char *dirName, char *msgBuf, int msgBufLen);
int gmoGetReadyL (const char *libName, char *msgBuf, int msgBufLen);
int gmoCreate    (gmoHandle_t *pgmo, char *msgBuf, int msgBufLen);
int gmoCreateD   (gmoHandle_t *pgmo, const char *dirName, char *msgBuf, int msgBufLen);
int gmoCreateL   (gmoHandle_t *pgmo, const char *libName, char *msgBuf, int msgBufLen);
int gmoFree      (gmoHandle_t *pgmo);

int gmoLibraryLoaded(void);
int gmoLibraryUnload(void);

int  gmoGetScreenIndicator   (void);
void gmoSetScreenIndicator   (int scrind);
int  gmoGetExceptionIndicator(void);
void gmoSetExceptionIndicator(int excind);
int  gmoGetExitIndicator     (void);
void gmoSetExitIndicator     (int extind);
gmoErrorCallback_t gmoGetErrorCallback(void);
void gmoSetErrorCallback(gmoErrorCallback_t func);
int  gmoGetAPIErrorCount     (void);
void gmoSetAPIErrorCount     (int ecnt);

void gmoErrorHandling(const char *msg);


#if defined(GMO_MAIN)    /* we must define some things only once */
# define GMO_FUNCPTR(NAME)  NAME##_t NAME = NULL
#else
# define GMO_FUNCPTR(NAME)  extern NAME##_t NAME
#endif


/* Prototypes for Dummy Functions */
int  GMO_CALLCONV d_gmoLoadDataLegacy (gmoHandle_t pgmo, char *msg);
int  GMO_CALLCONV d_gmoInitData (gmoHandle_t pgmo, int rows, int cols);
int  GMO_CALLCONV d_gmoCompleteData (gmoHandle_t pgmo, const char *instname);
int  GMO_CALLCONV d_gmoGetObjQ (gmoHandle_t pgmo, int *colIdx, int *rowIdx, double *coef);
int  GMO_CALLCONV d_gmoGetRowQ (gmoHandle_t pgmo, int si, int *colIdx, int *rowIdx, double *coef);
int  GMO_CALLCONV d_gmoDumpQMakerGDX (gmoHandle_t pgmo, const char *gdxfname);
int  GMO_CALLCONV d_gmoGetColStat (gmoHandle_t pgmo, int sj, int *jnz, int *jqnz, int *jnlnz, int *jobjnz);
int  GMO_CALLCONV d_gmoGetObjStat (gmoHandle_t pgmo, int *inz, int *iqnz, int *inlnz);
int  GMO_CALLCONV d_gmoGetRowStat (gmoHandle_t pgmo, int si, int *inz, int *iqnz, int *inlnz);
int  GMO_CALLCONV d_gmoGetMatrixCplex (gmoHandle_t pgmo, int *ColStart, int *ColLength, int *RowIndex, double *JacValue);
int  GMO_CALLCONV d_gmoGetMatrixCol (gmoHandle_t pgmo, int *ColStart, int *RowIndex, double *JacValue, int *NLFlag);
int  GMO_CALLCONV d_gmoGetObjVector (gmoHandle_t pgmo, double *ObjVector, int *NLFlag);
int  GMO_CALLCONV d_gmoGetObjSparse (gmoHandle_t pgmo, int *ColIndex, double *JacValue, int *NLFlag, int *NZ, int *NLNZ);
int  GMO_CALLCONV d_gmoGetRowSparse (gmoHandle_t pgmo, int si, int *ColIndex, double *JacValue, int *NLFlag, int *NZ, int *NLNZ);
int  GMO_CALLCONV d_gmoGetColSparse (gmoHandle_t pgmo, int sj, int *RowIndex, double *JacValue, int *NLFlag, int *NZ, int *NLNZ);
int  GMO_CALLCONV d_gmoGetMatrixRow (gmoHandle_t pgmo, int *RowStart, int *ColIndex, double *JacValue, int *NLFlag);
void  GMO_CALLCONV d_gmoGetSosCounts (gmoHandle_t pgmo, int *numSos1, int *numSos2, int *nzSos);
int  GMO_CALLCONV d_gmoGetSosConstraints (gmoHandle_t pgmo, int *sostype, int *sosbeg, int *sosind, double *soswt);
int  GMO_CALLCONV d_gmoGetVarSosSetOne (gmoHandle_t pgmo, int sj);
void  GMO_CALLCONV d_gmoGetColJacInfoOne (gmoHandle_t pgmo, int sj, void **jacp, double *aval, int *irow, int *nzind);
void  GMO_CALLCONV d_gmoGetRowJacInfoOne (gmoHandle_t pgmo, int si, void **jacp, double *aval, int *jcol, int *nzind);
int  GMO_CALLCONV d_gmoGetVarL (gmoHandle_t pgmo, double *X);
double  GMO_CALLCONV d_gmoGetVarLOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoSetVarL (gmoHandle_t pgmo, const double *X);
void  GMO_CALLCONV d_gmoSetVarLOne (gmoHandle_t pgmo, int sj, double value);
int  GMO_CALLCONV d_gmoGetVarM (gmoHandle_t pgmo, double *Dj);
double  GMO_CALLCONV d_gmoGetVarMOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoSetVarM (gmoHandle_t pgmo, const double *Dj);
char * GMO_CALLCONV d_gmoGetVarNameOne (gmoHandle_t pgmo, int sj, char *buf);
int  GMO_CALLCONV d_gmoGetVarLower (gmoHandle_t pgmo, double *LoVector);
double  GMO_CALLCONV d_gmoGetVarLowerOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoGetVarUpper (gmoHandle_t pgmo, double *UpVector);
double  GMO_CALLCONV d_gmoGetVarUpperOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoSetAltVarBounds (gmoHandle_t pgmo, const double *LoVector, const double *UpVector);
void  GMO_CALLCONV d_gmoSetAltVarLowerOne (gmoHandle_t pgmo, int sj, double value);
void  GMO_CALLCONV d_gmoSetAltVarUpperOne (gmoHandle_t pgmo, int sj, double value);
int  GMO_CALLCONV d_gmoGetVarType (gmoHandle_t pgmo, int *TypeVector);
int  GMO_CALLCONV d_gmoGetVarTypeOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoSetAltVarType (gmoHandle_t pgmo, const int *TypeVector);
void  GMO_CALLCONV d_gmoSetAltVarTypeOne (gmoHandle_t pgmo, int sj, int value);
int  GMO_CALLCONV d_gmoGetVarTypeCnt (gmoHandle_t pgmo, int vart);
void  GMO_CALLCONV d_gmoGetVarStat (gmoHandle_t pgmo, int *StatVector);
int  GMO_CALLCONV d_gmoGetVarStatOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoGetVarCStatOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoBasisIsFull (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoGetVarPrior (gmoHandle_t pgmo, double *BranchPrior);
double  GMO_CALLCONV d_gmoGetVarPriorOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoGetVarScale (gmoHandle_t pgmo, double *ScaleVector);
double  GMO_CALLCONV d_gmoGetVarScaleOne (gmoHandle_t pgmo, int sj);
double  GMO_CALLCONV d_gmoGetVarStageOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoGetEquL (gmoHandle_t pgmo, double *Mvector);
double  GMO_CALLCONV d_gmoGetEquLOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoSetEquL (gmoHandle_t pgmo, const double *Mvector);
int  GMO_CALLCONV d_gmoGetEquM (gmoHandle_t pgmo, double *PI);
double  GMO_CALLCONV d_gmoGetEquMOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoSetEquM (gmoHandle_t pgmo, const double *PI);
char * GMO_CALLCONV d_gmoGetEquNameOne (gmoHandle_t pgmo, int si, char *buf);
char * GMO_CALLCONV d_gmoGetObjName (gmoHandle_t pgmo, char *buf);
int  GMO_CALLCONV d_gmoGetRhs (gmoHandle_t pgmo, double *RhsVector);
double  GMO_CALLCONV d_gmoGetRhsOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoSetAltRHS (gmoHandle_t pgmo, const double *RhsVector);
void  GMO_CALLCONV d_gmoSetAltRHSOne (gmoHandle_t pgmo, int si, double value);
int  GMO_CALLCONV d_gmoGetEquSlack (gmoHandle_t pgmo, double *Mvector);
double  GMO_CALLCONV d_gmoGetEquSlackOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoSetEquSlack (gmoHandle_t pgmo, const double *Mvector);
int  GMO_CALLCONV d_gmoGetEquType (gmoHandle_t pgmo, int *TypeVector);
int  GMO_CALLCONV d_gmoGetEquTypeOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetEquTypeCnt (gmoHandle_t pgmo, int equt);
void  GMO_CALLCONV d_gmoGetEquStat (gmoHandle_t pgmo, int *StatVector);
int  GMO_CALLCONV d_gmoGetEquStatOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetEquCStatOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetEquMatch (gmoHandle_t pgmo, int *matchVector);
int  GMO_CALLCONV d_gmoGetEquMatchOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetEquScale (gmoHandle_t pgmo, double *ScaleVector);
double  GMO_CALLCONV d_gmoGetEquScaleOne (gmoHandle_t pgmo, int si);
double  GMO_CALLCONV d_gmoGetEquStageOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetEquOrderOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetRowQNZOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetRowQDiagNZOne (gmoHandle_t pgmo, int si);
void  GMO_CALLCONV d_gmoGetXLibCounts (gmoHandle_t pgmo, int *x_rows, int *x_cols, int *x_nzs);
double  GMO_CALLCONV d_gmoGetHeadnTail (gmoHandle_t pgmo, int headrec);
void  GMO_CALLCONV d_gmoSetHeadnTail (gmoHandle_t pgmo, int headrec, double value);
int  GMO_CALLCONV d_gmoSetEquPermutation (gmoHandle_t pgmo, int *permut);
int  GMO_CALLCONV d_gmoSetRvEquPermutation (gmoHandle_t pgmo, int *rvpermut, int len);
int  GMO_CALLCONV d_gmoSetVarPermutation (gmoHandle_t pgmo, int *permut);
int  GMO_CALLCONV d_gmoSetRvVarPermutation (gmoHandle_t pgmo, int *rvpermut, int len);
int  GMO_CALLCONV d_gmoSetNRowPerm (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoDirtySetMinosPerm (gmoHandle_t pgmo, int *mnl, int *nnl);
int  GMO_CALLCONV d_gmoDirtyExtractDefVar (gmoHandle_t pgmo, int *rowPiv, int *rowFree, int *colFix, int *ColNO, int *RowNO, double *DefPiv);
int  GMO_CALLCONV d_gmoEvalErrors (gmoHandle_t pgmo, int tidx);
int  GMO_CALLCONV d_gmoLastEvalErrors (gmoHandle_t pgmo, int tidx);
void  GMO_CALLCONV d_gmoIgnoreEvalErrors (gmoHandle_t pgmo, int ignerr, int tidx);
int  GMO_CALLCONV d_gmoEvalNewPoint (gmoHandle_t pgmo, const double *X);
int  GMO_CALLCONV d_gmoEvalSync (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoEvalFunc (gmoHandle_t pgmo, int si, const double *X, double *f, int *numErr);
int  GMO_CALLCONV d_gmoEvalFuncInt (gmoHandle_t pgmo, int si, double *f, int *numErr);
int  GMO_CALLCONV d_gmoEvalFuncL (gmoHandle_t pgmo, int si, const double *X, double *fnl);
int  GMO_CALLCONV d_gmoEvalFuncNL (gmoHandle_t pgmo, int si, const double *X, double *fnl, int tidx);
int  GMO_CALLCONV d_gmoEvalFuncGrad (gmoHandle_t pgmo, int si, const double *X, double *f);
int  GMO_CALLCONV d_gmoEvalFuncGradInt (gmoHandle_t pgmo, int si, double *f);
int  GMO_CALLCONV d_gmoEvalGrad (gmoHandle_t pgmo, int si, const double *X, double *f, double *g, double *gx, int *numErr);
int  GMO_CALLCONV d_gmoEvalGradNL (gmoHandle_t pgmo, int si, const double *X, double *fnl, double *g, double *gxnl, int tidx);
int  GMO_CALLCONV d_gmoEvalObjFunc (gmoHandle_t pgmo, const double *X, double *f, int *numErr);
int  GMO_CALLCONV d_gmoEvalObjFuncNL (gmoHandle_t pgmo, const double *X, double *fnl, int *numErr);
int  GMO_CALLCONV d_gmoEvalObjGrad (gmoHandle_t pgmo, const double *X, double *f, double *g, double *gx, int *numErr);
int  GMO_CALLCONV d_gmoEvalObjGradNL (gmoHandle_t pgmo, const double *X, double *fnl, double *g, double *gxnl, int *numErr);
int  GMO_CALLCONV d_gmoEvalFuncInterval (gmoHandle_t pgmo, int si, const double *xmin, const double *xmax, double *fmin, double *fmax);
int  GMO_CALLCONV d_gmoEvalGradInterval (gmoHandle_t pgmo, int si, const double *xmin, const double *xmax, double *fmin, double *fmax, double *jmin, double *jmax);
int  GMO_CALLCONV d_gmoSetSolution2 (gmoHandle_t pgmo, const double *X, const double *PI);
int  GMO_CALLCONV d_gmoSetSolution (gmoHandle_t pgmo, const double *X, const double *Dj, const double *PI, const double *E);
int  GMO_CALLCONV d_gmoSetSolution8 (gmoHandle_t pgmo, const double *X, const double *Dj, const double *PI, const double *E, int *XB, int *XS, int *YB, int *YS);
int  GMO_CALLCONV d_gmoSetSolutionFixer (gmoHandle_t pgmo, int modelStatHint, const double *X, const double *PI, const int *XB, const int *YB);
int  GMO_CALLCONV d_gmoGetSolutionVarRec (gmoHandle_t pgmo, int sj, double *X, double *Dj, int *XB, int *XS);
int  GMO_CALLCONV d_gmoSetSolutionVarRec (gmoHandle_t pgmo, int sj, double X, double Dj, int XB, int XS);
int  GMO_CALLCONV d_gmoGetSolutionEquRec (gmoHandle_t pgmo, int si, double *E, double *PI, int *YB, int *YS);
int  GMO_CALLCONV d_gmoSetSolutionEquRec (gmoHandle_t pgmo, int si, double E, double PI, int YB, int YS);
int  GMO_CALLCONV d_gmoSetSolutionStatus (gmoHandle_t pgmo, int *XB, int *XS, int *YB, int *YS);
int  GMO_CALLCONV d_gmoCompleteSolution (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoLoadSolutionLegacy (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoUnloadSolutionLegacy (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoLoadSolutionGDX (gmoHandle_t pgmo, const char *gdxfname, int rows, int cols, int ht);
int  GMO_CALLCONV d_gmoUnloadSolutionGDX (gmoHandle_t pgmo, const char *gdxfname, int rows, int cols, int ht);
int  GMO_CALLCONV d_gmoLastError (gmoHandle_t pgmo, char *msg);
void  GMO_CALLCONV d_gmoClearError (gmoHandle_t pgmo);
double  GMO_CALLCONV d_gmoMemUsed (gmoHandle_t pgmo);
double  GMO_CALLCONV d_gmoPeakMemUsed (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoGetiSolver (gmoHandle_t pgmo, int mi);
int  GMO_CALLCONV d_gmoGetjSolver (gmoHandle_t pgmo, int mj);
int  GMO_CALLCONV d_gmoGetiModel (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetjModel (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoAddRow (gmoHandle_t pgmo, int typEqu, int matchEqu, double slackEqu, double scaleEqu, double rhsEqu, double mEqu, int basEqu, int nzEqu, const int *colArr, const double *jacArr, const int *nlArr);
int  GMO_CALLCONV d_gmoAddCol (gmoHandle_t pgmo, int typVar, double loVar, double lVar, double upVar, double mVar, int basVar, int sosVar, double priorVar, double scaleVar, int nzVar, const int *rowArr, const double *jacArr, const int *nlArr);
void  GMO_CALLCONV d_gmoCompleteJacs (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoCrudeness (gmoHandle_t pgmo);
void * GMO_CALLCONV d_gmoDict (gmoHandle_t pgmo);
void * GMO_CALLCONV d_gmoEnvironment (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoRegisterEnvironment (gmoHandle_t pgmo, void *gevPtr, char *msg);
int  GMO_CALLCONV d_gmoEvalGradNLInt (gmoHandle_t pgmo, double *rhsdelta, int storejacupd, int *numErr);
int  GMO_CALLCONV d_gmoGetJacUpdate (gmoHandle_t pgmo, int *ivec, int *jvec, double *JacValue, int *nrjacupd);
int  GMO_CALLCONV d_gmoGetSolveStatusTxt (gmoHandle_t pgmo, int solvestat, char *sstxt);
int  GMO_CALLCONV d_gmoGetModelStatusTxt (gmoHandle_t pgmo, int modelstat, char *mstxt);
int  GMO_CALLCONV d_gmoGetModelTypeTxt (gmoHandle_t pgmo, char *mttxt);
int  GMO_CALLCONV d_gmoGetHeadNTailTxt (gmoHandle_t pgmo, int htrec, char *httxt);
int  GMO_CALLCONV d_gmoDirtyGetRowFNLInstr (gmoHandle_t pgmo, int si, int *len, int *opcode, int *field);
int  GMO_CALLCONV d_gmoDirtyGetObjFNLInstr (gmoHandle_t pgmo, int *len, int *opcode, int *field);
int  GMO_CALLCONV d_gmoDirtySetRowFNLInstr (gmoHandle_t pgmo, int si, int len, const int *opcode, const int *field, void *poolx);
int  GMO_CALLCONV d_gmoSetNLObject (gmoHandle_t pgmo, void *NLObj, void *NLPool);
int  GMO_CALLCONV d_gmoHessLoad (gmoHandle_t pgmo, int maxJacMult, int *do2dir, int *doHess);
int  GMO_CALLCONV d_gmoHessUnload (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoHessDim (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoHessNz (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoHessStruct (gmoHandle_t pgmo, int si, int *HRindex, int *HCindex, int *HessDim, int *HessNz);
int  GMO_CALLCONV d_gmoHessValue (gmoHandle_t pgmo, int si, int *HRindex, int *HCindex, int *HessDim, int *HessNz, const double *Xval, double *Hval, int *numErr);
int  GMO_CALLCONV d_gmoHessVec (gmoHandle_t pgmo, int si, const double *X, const double *dx, double *Wdx, int *numErr);
int  GMO_CALLCONV d_gmoHessLagStruct (gmoHandle_t pgmo, int *WRindex, int *WCindex);
int  GMO_CALLCONV d_gmoHessLagValue (gmoHandle_t pgmo, const double *X, const double *u, double *w, double objWeight, double conWeight, int *numErr);
int  GMO_CALLCONV d_gmoHessLagVec (gmoHandle_t pgmo, const double *X, const double *u, const double *dx, double *Wdx, double objWeight, double conWeight, int *numErr);
int  GMO_CALLCONV d_gmoPrepareAllSolToGDX (gmoHandle_t pgmo, const char *gdxfname, void *scengdx, int dictid);
int  GMO_CALLCONV d_gmoAddSolutionToGDX (gmoHandle_t pgmo, const char *scenuel);
int  GMO_CALLCONV d_gmoWriteSolDone (gmoHandle_t pgmo, char *msg);
void * GMO_CALLCONV d_gmoViewStore (gmoHandle_t pgmo);
void  GMO_CALLCONV d_gmoViewRestore (gmoHandle_t pgmo, void **viewptr);
int  GMO_CALLCONV d_gmoLoadEMPInfo (gmoHandle_t pgmo, const char *empinfofn);
int  GMO_CALLCONV d_gmoGetEquVI (gmoHandle_t pgmo, int *Mvector);
int  GMO_CALLCONV d_gmoGetEquVIOne (gmoHandle_t pgmo, int si);
int  GMO_CALLCONV d_gmoGetVarVI (gmoHandle_t pgmo, int *Nvector);
int  GMO_CALLCONV d_gmoGetVarVIOne (gmoHandle_t pgmo, int sj);
int  GMO_CALLCONV d_gmoGetAgentType (gmoHandle_t pgmo, int *NumAgentVector);
int  GMO_CALLCONV d_gmoGetAgentTypeOne (gmoHandle_t pgmo, int a);
int  GMO_CALLCONV d_gmoGetBiLevelInfo (gmoHandle_t pgmo, int *Nvector, int *Mvector);
char * GMO_CALLCONV d_gmoNameModel (gmoHandle_t pgmo, char *buf);
void GMO_CALLCONV d_gmoNameModelSet (gmoHandle_t pgmo, const char *x);
int  GMO_CALLCONV d_gmoObjNZ (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoObjNLNZ (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoObjStyle (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoObjStyleSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoGetObjOrder (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoErrorMethod (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoErrorMethodSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoInterface (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoInterfaceSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoIndexBase (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoIndexBaseSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoObjReform (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoObjReformSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoEmptyOut (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoEmptyOutSet (gmoHandle_t pgmo, const int x);
double  GMO_CALLCONV d_gmoObjConst (gmoHandle_t pgmo);
double  GMO_CALLCONV d_gmoObjJacVal (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoModelStat (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoModelStatSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoSolveStat (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoSolveStatSet (gmoHandle_t pgmo, const int x);
double  GMO_CALLCONV d_gmoPinf (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoPinfSet (gmoHandle_t pgmo, const double x);
double  GMO_CALLCONV d_gmoMinf (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoMinfSet (gmoHandle_t pgmo, const double x);
double  GMO_CALLCONV d_gmoInfTol (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoInfTolSet (gmoHandle_t pgmo, const double x);
double  GMO_CALLCONV d_gmoOptTol (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoOptTolSet (gmoHandle_t pgmo, const double x);
int  GMO_CALLCONV d_gmoAltBounds (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoAltBoundsSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoAltRHS (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoAltRHSSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoAltVarTypes (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoAltVarTypesSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoForceLinear (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoForceLinearSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoForceCont (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoForceContSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoIsQP (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoNDisc (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoMaxQnz (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoQRows (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoWantQ (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoWantQSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoObjQNZ (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoObjQDiagNZ (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoNLCodeFun (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoNLCodeFunSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoMaxSingleFNL (gmoHandle_t pgmo);
void * GMO_CALLCONV d_gmoPCodeFun (gmoHandle_t pgmo);
void * GMO_CALLCONV d_gmoPPool (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoNFixed (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoPermuteCols (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoPermuteColsSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoPermuteRows (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoPermuteRowsSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoMaxThreads (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoMaxThreadsSet (gmoHandle_t pgmo, const int x);
double  GMO_CALLCONV d_gmoQNaN (gmoHandle_t pgmo);
double  GMO_CALLCONV d_gmoValNA (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoValNAInt (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoIgnXCDeriv (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoIgnXCDerivSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoHessMaxDim (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoHessMaxNz (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoHessLagDim (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoHessLagNz (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoHessLagDiagNz (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoNumVIFunc (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoNumAgents (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoModelType (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoModelTypeSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoM (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoN (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoScaleOpt (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoScaleOptSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoSense (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoSenseSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoObjVar (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoObjVarSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoOptFile (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoOptFileSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoPriorOpt (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoPriorOptSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoNLConst (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoNLConstSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoNZ (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoNZSet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoNLNZ (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoNLM (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoNLN (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoObjRow (gmoHandle_t pgmo);
int  GMO_CALLCONV d_gmoDictionary (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoDictionarySet (gmoHandle_t pgmo, const int x);
int  GMO_CALLCONV d_gmoHaveBasis (gmoHandle_t pgmo);
void GMO_CALLCONV d_gmoHaveBasisSet (gmoHandle_t pgmo, const int x);
char * GMO_CALLCONV d_gmoNameOptFile (gmoHandle_t pgmo, char *buf);
void GMO_CALLCONV d_gmoNameOptFileSet (gmoHandle_t pgmo, const char *x);
char * GMO_CALLCONV d_gmoNameSolFile (gmoHandle_t pgmo, char *buf);
void GMO_CALLCONV d_gmoNameSolFileSet (gmoHandle_t pgmo, const char *x);
char * GMO_CALLCONV d_gmoNameXLib (gmoHandle_t pgmo, char *buf);
void GMO_CALLCONV d_gmoNameXLibSet (gmoHandle_t pgmo, const char *x);
char * GMO_CALLCONV d_gmoNameMatFile (gmoHandle_t pgmo, char *buf);
void GMO_CALLCONV d_gmoNameMatFileSet (gmoHandle_t pgmo, const char *x);
char * GMO_CALLCONV d_gmoNameDict (gmoHandle_t pgmo, char *buf);
void GMO_CALLCONV d_gmoNameDictSet (gmoHandle_t pgmo, const char *x);
char * GMO_CALLCONV d_gmoNameParams (gmoHandle_t pgmo, char *buf);
void GMO_CALLCONV d_gmoNameParamsSet (gmoHandle_t pgmo, const char *x);
char * GMO_CALLCONV d_gmoNameInput (gmoHandle_t pgmo, char *buf);

typedef int  (GMO_CALLCONV *gmoLoadDataLegacy_t) (gmoHandle_t pgmo, char *msg);
GMO_FUNCPTR(gmoLoadDataLegacy);
typedef int  (GMO_CALLCONV *gmoInitData_t) (gmoHandle_t pgmo, int rows, int cols);
GMO_FUNCPTR(gmoInitData);
typedef int  (GMO_CALLCONV *gmoCompleteData_t) (gmoHandle_t pgmo, const char *instname);
GMO_FUNCPTR(gmoCompleteData);
typedef int  (GMO_CALLCONV *gmoGetObjQ_t) (gmoHandle_t pgmo, int *colIdx, int *rowIdx, double *coef);
GMO_FUNCPTR(gmoGetObjQ);
typedef int  (GMO_CALLCONV *gmoGetRowQ_t) (gmoHandle_t pgmo, int si, int *colIdx, int *rowIdx, double *coef);
GMO_FUNCPTR(gmoGetRowQ);
typedef int  (GMO_CALLCONV *gmoDumpQMakerGDX_t) (gmoHandle_t pgmo, const char *gdxfname);
GMO_FUNCPTR(gmoDumpQMakerGDX);
typedef int  (GMO_CALLCONV *gmoGetColStat_t) (gmoHandle_t pgmo, int sj, int *jnz, int *jqnz, int *jnlnz, int *jobjnz);
GMO_FUNCPTR(gmoGetColStat);
typedef int  (GMO_CALLCONV *gmoGetObjStat_t) (gmoHandle_t pgmo, int *inz, int *iqnz, int *inlnz);
GMO_FUNCPTR(gmoGetObjStat);
typedef int  (GMO_CALLCONV *gmoGetRowStat_t) (gmoHandle_t pgmo, int si, int *inz, int *iqnz, int *inlnz);
GMO_FUNCPTR(gmoGetRowStat);
typedef int  (GMO_CALLCONV *gmoGetMatrixCplex_t) (gmoHandle_t pgmo, int *ColStart, int *ColLength, int *RowIndex, double *JacValue);
GMO_FUNCPTR(gmoGetMatrixCplex);
typedef int  (GMO_CALLCONV *gmoGetMatrixCol_t) (gmoHandle_t pgmo, int *ColStart, int *RowIndex, double *JacValue, int *NLFlag);
GMO_FUNCPTR(gmoGetMatrixCol);
typedef int  (GMO_CALLCONV *gmoGetObjVector_t) (gmoHandle_t pgmo, double *ObjVector, int *NLFlag);
GMO_FUNCPTR(gmoGetObjVector);
typedef int  (GMO_CALLCONV *gmoGetObjSparse_t) (gmoHandle_t pgmo, int *ColIndex, double *JacValue, int *NLFlag, int *NZ, int *NLNZ);
GMO_FUNCPTR(gmoGetObjSparse);
typedef int  (GMO_CALLCONV *gmoGetRowSparse_t) (gmoHandle_t pgmo, int si, int *ColIndex, double *JacValue, int *NLFlag, int *NZ, int *NLNZ);
GMO_FUNCPTR(gmoGetRowSparse);
typedef int  (GMO_CALLCONV *gmoGetColSparse_t) (gmoHandle_t pgmo, int sj, int *RowIndex, double *JacValue, int *NLFlag, int *NZ, int *NLNZ);
GMO_FUNCPTR(gmoGetColSparse);
typedef int  (GMO_CALLCONV *gmoGetMatrixRow_t) (gmoHandle_t pgmo, int *RowStart, int *ColIndex, double *JacValue, int *NLFlag);
GMO_FUNCPTR(gmoGetMatrixRow);
typedef void  (GMO_CALLCONV *gmoGetSosCounts_t) (gmoHandle_t pgmo, int *numSos1, int *numSos2, int *nzSos);
GMO_FUNCPTR(gmoGetSosCounts);
typedef int  (GMO_CALLCONV *gmoGetSosConstraints_t) (gmoHandle_t pgmo, int *sostype, int *sosbeg, int *sosind, double *soswt);
GMO_FUNCPTR(gmoGetSosConstraints);
typedef int  (GMO_CALLCONV *gmoGetVarSosSetOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarSosSetOne);
typedef void  (GMO_CALLCONV *gmoGetColJacInfoOne_t) (gmoHandle_t pgmo, int sj, void **jacp, double *aval, int *irow, int *nzind);
GMO_FUNCPTR(gmoGetColJacInfoOne);
typedef void  (GMO_CALLCONV *gmoGetRowJacInfoOne_t) (gmoHandle_t pgmo, int si, void **jacp, double *aval, int *jcol, int *nzind);
GMO_FUNCPTR(gmoGetRowJacInfoOne);
typedef int  (GMO_CALLCONV *gmoGetVarL_t) (gmoHandle_t pgmo, double *X);
GMO_FUNCPTR(gmoGetVarL);
typedef double  (GMO_CALLCONV *gmoGetVarLOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarLOne);
typedef int  (GMO_CALLCONV *gmoSetVarL_t) (gmoHandle_t pgmo, const double *X);
GMO_FUNCPTR(gmoSetVarL);
typedef void  (GMO_CALLCONV *gmoSetVarLOne_t) (gmoHandle_t pgmo, int sj, double value);
GMO_FUNCPTR(gmoSetVarLOne);
typedef int  (GMO_CALLCONV *gmoGetVarM_t) (gmoHandle_t pgmo, double *Dj);
GMO_FUNCPTR(gmoGetVarM);
typedef double  (GMO_CALLCONV *gmoGetVarMOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarMOne);
typedef int  (GMO_CALLCONV *gmoSetVarM_t) (gmoHandle_t pgmo, const double *Dj);
GMO_FUNCPTR(gmoSetVarM);
typedef char * (GMO_CALLCONV *gmoGetVarNameOne_t) (gmoHandle_t pgmo, int sj, char *buf);
GMO_FUNCPTR(gmoGetVarNameOne);
typedef int  (GMO_CALLCONV *gmoGetVarLower_t) (gmoHandle_t pgmo, double *LoVector);
GMO_FUNCPTR(gmoGetVarLower);
typedef double  (GMO_CALLCONV *gmoGetVarLowerOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarLowerOne);
typedef int  (GMO_CALLCONV *gmoGetVarUpper_t) (gmoHandle_t pgmo, double *UpVector);
GMO_FUNCPTR(gmoGetVarUpper);
typedef double  (GMO_CALLCONV *gmoGetVarUpperOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarUpperOne);
typedef int  (GMO_CALLCONV *gmoSetAltVarBounds_t) (gmoHandle_t pgmo, const double *LoVector, const double *UpVector);
GMO_FUNCPTR(gmoSetAltVarBounds);
typedef void  (GMO_CALLCONV *gmoSetAltVarLowerOne_t) (gmoHandle_t pgmo, int sj, double value);
GMO_FUNCPTR(gmoSetAltVarLowerOne);
typedef void  (GMO_CALLCONV *gmoSetAltVarUpperOne_t) (gmoHandle_t pgmo, int sj, double value);
GMO_FUNCPTR(gmoSetAltVarUpperOne);
typedef int  (GMO_CALLCONV *gmoGetVarType_t) (gmoHandle_t pgmo, int *TypeVector);
GMO_FUNCPTR(gmoGetVarType);
typedef int  (GMO_CALLCONV *gmoGetVarTypeOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarTypeOne);
typedef int  (GMO_CALLCONV *gmoSetAltVarType_t) (gmoHandle_t pgmo, const int *TypeVector);
GMO_FUNCPTR(gmoSetAltVarType);
typedef void  (GMO_CALLCONV *gmoSetAltVarTypeOne_t) (gmoHandle_t pgmo, int sj, int value);
GMO_FUNCPTR(gmoSetAltVarTypeOne);
typedef int  (GMO_CALLCONV *gmoGetVarTypeCnt_t) (gmoHandle_t pgmo, int vart);
GMO_FUNCPTR(gmoGetVarTypeCnt);
typedef void  (GMO_CALLCONV *gmoGetVarStat_t) (gmoHandle_t pgmo, int *StatVector);
GMO_FUNCPTR(gmoGetVarStat);
typedef int  (GMO_CALLCONV *gmoGetVarStatOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarStatOne);
typedef int  (GMO_CALLCONV *gmoGetVarCStatOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarCStatOne);
typedef int  (GMO_CALLCONV *gmoBasisIsFull_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoBasisIsFull);
typedef int  (GMO_CALLCONV *gmoGetVarPrior_t) (gmoHandle_t pgmo, double *BranchPrior);
GMO_FUNCPTR(gmoGetVarPrior);
typedef double  (GMO_CALLCONV *gmoGetVarPriorOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarPriorOne);
typedef int  (GMO_CALLCONV *gmoGetVarScale_t) (gmoHandle_t pgmo, double *ScaleVector);
GMO_FUNCPTR(gmoGetVarScale);
typedef double  (GMO_CALLCONV *gmoGetVarScaleOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarScaleOne);
typedef double  (GMO_CALLCONV *gmoGetVarStageOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarStageOne);
typedef int  (GMO_CALLCONV *gmoGetEquL_t) (gmoHandle_t pgmo, double *Mvector);
GMO_FUNCPTR(gmoGetEquL);
typedef double  (GMO_CALLCONV *gmoGetEquLOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquLOne);
typedef int  (GMO_CALLCONV *gmoSetEquL_t) (gmoHandle_t pgmo, const double *Mvector);
GMO_FUNCPTR(gmoSetEquL);
typedef int  (GMO_CALLCONV *gmoGetEquM_t) (gmoHandle_t pgmo, double *PI);
GMO_FUNCPTR(gmoGetEquM);
typedef double  (GMO_CALLCONV *gmoGetEquMOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquMOne);
typedef int  (GMO_CALLCONV *gmoSetEquM_t) (gmoHandle_t pgmo, const double *PI);
GMO_FUNCPTR(gmoSetEquM);
typedef char * (GMO_CALLCONV *gmoGetEquNameOne_t) (gmoHandle_t pgmo, int si, char *buf);
GMO_FUNCPTR(gmoGetEquNameOne);
typedef char * (GMO_CALLCONV *gmoGetObjName_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoGetObjName);
typedef int  (GMO_CALLCONV *gmoGetRhs_t) (gmoHandle_t pgmo, double *RhsVector);
GMO_FUNCPTR(gmoGetRhs);
typedef double  (GMO_CALLCONV *gmoGetRhsOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetRhsOne);
typedef int  (GMO_CALLCONV *gmoSetAltRHS_t) (gmoHandle_t pgmo, const double *RhsVector);
GMO_FUNCPTR(gmoSetAltRHS);
typedef void  (GMO_CALLCONV *gmoSetAltRHSOne_t) (gmoHandle_t pgmo, int si, double value);
GMO_FUNCPTR(gmoSetAltRHSOne);
typedef int  (GMO_CALLCONV *gmoGetEquSlack_t) (gmoHandle_t pgmo, double *Mvector);
GMO_FUNCPTR(gmoGetEquSlack);
typedef double  (GMO_CALLCONV *gmoGetEquSlackOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquSlackOne);
typedef int  (GMO_CALLCONV *gmoSetEquSlack_t) (gmoHandle_t pgmo, const double *Mvector);
GMO_FUNCPTR(gmoSetEquSlack);
typedef int  (GMO_CALLCONV *gmoGetEquType_t) (gmoHandle_t pgmo, int *TypeVector);
GMO_FUNCPTR(gmoGetEquType);
typedef int  (GMO_CALLCONV *gmoGetEquTypeOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquTypeOne);
typedef int  (GMO_CALLCONV *gmoGetEquTypeCnt_t) (gmoHandle_t pgmo, int equt);
GMO_FUNCPTR(gmoGetEquTypeCnt);
typedef void  (GMO_CALLCONV *gmoGetEquStat_t) (gmoHandle_t pgmo, int *StatVector);
GMO_FUNCPTR(gmoGetEquStat);
typedef int  (GMO_CALLCONV *gmoGetEquStatOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquStatOne);
typedef int  (GMO_CALLCONV *gmoGetEquCStatOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquCStatOne);
typedef int  (GMO_CALLCONV *gmoGetEquMatch_t) (gmoHandle_t pgmo, int *matchVector);
GMO_FUNCPTR(gmoGetEquMatch);
typedef int  (GMO_CALLCONV *gmoGetEquMatchOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquMatchOne);
typedef int  (GMO_CALLCONV *gmoGetEquScale_t) (gmoHandle_t pgmo, double *ScaleVector);
GMO_FUNCPTR(gmoGetEquScale);
typedef double  (GMO_CALLCONV *gmoGetEquScaleOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquScaleOne);
typedef double  (GMO_CALLCONV *gmoGetEquStageOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquStageOne);
typedef int  (GMO_CALLCONV *gmoGetEquOrderOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquOrderOne);
typedef int  (GMO_CALLCONV *gmoGetRowQNZOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetRowQNZOne);
typedef int  (GMO_CALLCONV *gmoGetRowQDiagNZOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetRowQDiagNZOne);
typedef void  (GMO_CALLCONV *gmoGetXLibCounts_t) (gmoHandle_t pgmo, int *x_rows, int *x_cols, int *x_nzs);
GMO_FUNCPTR(gmoGetXLibCounts);
typedef double  (GMO_CALLCONV *gmoGetHeadnTail_t) (gmoHandle_t pgmo, int headrec);
GMO_FUNCPTR(gmoGetHeadnTail);
typedef void  (GMO_CALLCONV *gmoSetHeadnTail_t) (gmoHandle_t pgmo, int headrec, double value);
GMO_FUNCPTR(gmoSetHeadnTail);
typedef int  (GMO_CALLCONV *gmoSetEquPermutation_t) (gmoHandle_t pgmo, int *permut);
GMO_FUNCPTR(gmoSetEquPermutation);
typedef int  (GMO_CALLCONV *gmoSetRvEquPermutation_t) (gmoHandle_t pgmo, int *rvpermut, int len);
GMO_FUNCPTR(gmoSetRvEquPermutation);
typedef int  (GMO_CALLCONV *gmoSetVarPermutation_t) (gmoHandle_t pgmo, int *permut);
GMO_FUNCPTR(gmoSetVarPermutation);
typedef int  (GMO_CALLCONV *gmoSetRvVarPermutation_t) (gmoHandle_t pgmo, int *rvpermut, int len);
GMO_FUNCPTR(gmoSetRvVarPermutation);
typedef int  (GMO_CALLCONV *gmoSetNRowPerm_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoSetNRowPerm);
typedef int  (GMO_CALLCONV *gmoDirtySetMinosPerm_t) (gmoHandle_t pgmo, int *mnl, int *nnl);
GMO_FUNCPTR(gmoDirtySetMinosPerm);
typedef int  (GMO_CALLCONV *gmoDirtyExtractDefVar_t) (gmoHandle_t pgmo, int *rowPiv, int *rowFree, int *colFix, int *ColNO, int *RowNO, double *DefPiv);
GMO_FUNCPTR(gmoDirtyExtractDefVar);
typedef int  (GMO_CALLCONV *gmoEvalErrors_t) (gmoHandle_t pgmo, int tidx);
GMO_FUNCPTR(gmoEvalErrors);
typedef int  (GMO_CALLCONV *gmoLastEvalErrors_t) (gmoHandle_t pgmo, int tidx);
GMO_FUNCPTR(gmoLastEvalErrors);
typedef void  (GMO_CALLCONV *gmoIgnoreEvalErrors_t) (gmoHandle_t pgmo, int ignerr, int tidx);
GMO_FUNCPTR(gmoIgnoreEvalErrors);
typedef int  (GMO_CALLCONV *gmoEvalNewPoint_t) (gmoHandle_t pgmo, const double *X);
GMO_FUNCPTR(gmoEvalNewPoint);
typedef int  (GMO_CALLCONV *gmoEvalSync_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoEvalSync);
typedef int  (GMO_CALLCONV *gmoEvalFunc_t) (gmoHandle_t pgmo, int si, const double *X, double *f, int *numErr);
GMO_FUNCPTR(gmoEvalFunc);
typedef int  (GMO_CALLCONV *gmoEvalFuncInt_t) (gmoHandle_t pgmo, int si, double *f, int *numErr);
GMO_FUNCPTR(gmoEvalFuncInt);
typedef int  (GMO_CALLCONV *gmoEvalFuncL_t) (gmoHandle_t pgmo, int si, const double *X, double *fnl);
GMO_FUNCPTR(gmoEvalFuncL);
typedef int  (GMO_CALLCONV *gmoEvalFuncNL_t) (gmoHandle_t pgmo, int si, const double *X, double *fnl, int tidx);
GMO_FUNCPTR(gmoEvalFuncNL);
typedef int  (GMO_CALLCONV *gmoEvalFuncGrad_t) (gmoHandle_t pgmo, int si, const double *X, double *f);
GMO_FUNCPTR(gmoEvalFuncGrad);
typedef int  (GMO_CALLCONV *gmoEvalFuncGradInt_t) (gmoHandle_t pgmo, int si, double *f);
GMO_FUNCPTR(gmoEvalFuncGradInt);
typedef int  (GMO_CALLCONV *gmoEvalGrad_t) (gmoHandle_t pgmo, int si, const double *X, double *f, double *g, double *gx, int *numErr);
GMO_FUNCPTR(gmoEvalGrad);
typedef int  (GMO_CALLCONV *gmoEvalGradNL_t) (gmoHandle_t pgmo, int si, const double *X, double *fnl, double *g, double *gxnl, int tidx);
GMO_FUNCPTR(gmoEvalGradNL);
typedef int  (GMO_CALLCONV *gmoEvalObjFunc_t) (gmoHandle_t pgmo, const double *X, double *f, int *numErr);
GMO_FUNCPTR(gmoEvalObjFunc);
typedef int  (GMO_CALLCONV *gmoEvalObjFuncNL_t) (gmoHandle_t pgmo, const double *X, double *fnl, int *numErr);
GMO_FUNCPTR(gmoEvalObjFuncNL);
typedef int  (GMO_CALLCONV *gmoEvalObjGrad_t) (gmoHandle_t pgmo, const double *X, double *f, double *g, double *gx, int *numErr);
GMO_FUNCPTR(gmoEvalObjGrad);
typedef int  (GMO_CALLCONV *gmoEvalObjGradNL_t) (gmoHandle_t pgmo, const double *X, double *fnl, double *g, double *gxnl, int *numErr);
GMO_FUNCPTR(gmoEvalObjGradNL);
typedef int  (GMO_CALLCONV *gmoEvalFuncInterval_t) (gmoHandle_t pgmo, int si, const double *xmin, const double *xmax, double *fmin, double *fmax);
GMO_FUNCPTR(gmoEvalFuncInterval);
typedef int  (GMO_CALLCONV *gmoEvalGradInterval_t) (gmoHandle_t pgmo, int si, const double *xmin, const double *xmax, double *fmin, double *fmax, double *jmin, double *jmax);
GMO_FUNCPTR(gmoEvalGradInterval);
typedef int  (GMO_CALLCONV *gmoSetSolution2_t) (gmoHandle_t pgmo, const double *X, const double *PI);
GMO_FUNCPTR(gmoSetSolution2);
typedef int  (GMO_CALLCONV *gmoSetSolution_t) (gmoHandle_t pgmo, const double *X, const double *Dj, const double *PI, const double *E);
GMO_FUNCPTR(gmoSetSolution);
typedef int  (GMO_CALLCONV *gmoSetSolution8_t) (gmoHandle_t pgmo, const double *X, const double *Dj, const double *PI, const double *E, int *XB, int *XS, int *YB, int *YS);
GMO_FUNCPTR(gmoSetSolution8);
typedef int  (GMO_CALLCONV *gmoSetSolutionFixer_t) (gmoHandle_t pgmo, int modelStatHint, const double *X, const double *PI, const int *XB, const int *YB);
GMO_FUNCPTR(gmoSetSolutionFixer);
typedef int  (GMO_CALLCONV *gmoGetSolutionVarRec_t) (gmoHandle_t pgmo, int sj, double *X, double *Dj, int *XB, int *XS);
GMO_FUNCPTR(gmoGetSolutionVarRec);
typedef int  (GMO_CALLCONV *gmoSetSolutionVarRec_t) (gmoHandle_t pgmo, int sj, double X, double Dj, int XB, int XS);
GMO_FUNCPTR(gmoSetSolutionVarRec);
typedef int  (GMO_CALLCONV *gmoGetSolutionEquRec_t) (gmoHandle_t pgmo, int si, double *E, double *PI, int *YB, int *YS);
GMO_FUNCPTR(gmoGetSolutionEquRec);
typedef int  (GMO_CALLCONV *gmoSetSolutionEquRec_t) (gmoHandle_t pgmo, int si, double E, double PI, int YB, int YS);
GMO_FUNCPTR(gmoSetSolutionEquRec);
typedef int  (GMO_CALLCONV *gmoSetSolutionStatus_t) (gmoHandle_t pgmo, int *XB, int *XS, int *YB, int *YS);
GMO_FUNCPTR(gmoSetSolutionStatus);
typedef int  (GMO_CALLCONV *gmoCompleteSolution_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoCompleteSolution);
typedef int  (GMO_CALLCONV *gmoLoadSolutionLegacy_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoLoadSolutionLegacy);
typedef int  (GMO_CALLCONV *gmoUnloadSolutionLegacy_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoUnloadSolutionLegacy);
typedef int  (GMO_CALLCONV *gmoLoadSolutionGDX_t) (gmoHandle_t pgmo, const char *gdxfname, int rows, int cols, int ht);
GMO_FUNCPTR(gmoLoadSolutionGDX);
typedef int  (GMO_CALLCONV *gmoUnloadSolutionGDX_t) (gmoHandle_t pgmo, const char *gdxfname, int rows, int cols, int ht);
GMO_FUNCPTR(gmoUnloadSolutionGDX);
typedef int  (GMO_CALLCONV *gmoLastError_t) (gmoHandle_t pgmo, char *msg);
GMO_FUNCPTR(gmoLastError);
typedef void  (GMO_CALLCONV *gmoClearError_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoClearError);
typedef double  (GMO_CALLCONV *gmoMemUsed_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoMemUsed);
typedef double  (GMO_CALLCONV *gmoPeakMemUsed_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoPeakMemUsed);
typedef int  (GMO_CALLCONV *gmoGetiSolver_t) (gmoHandle_t pgmo, int mi);
GMO_FUNCPTR(gmoGetiSolver);
typedef int  (GMO_CALLCONV *gmoGetjSolver_t) (gmoHandle_t pgmo, int mj);
GMO_FUNCPTR(gmoGetjSolver);
typedef int  (GMO_CALLCONV *gmoGetiModel_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetiModel);
typedef int  (GMO_CALLCONV *gmoGetjModel_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetjModel);
typedef int  (GMO_CALLCONV *gmoAddRow_t) (gmoHandle_t pgmo, int typEqu, int matchEqu, double slackEqu, double scaleEqu, double rhsEqu, double mEqu, int basEqu, int nzEqu, const int *colArr, const double *jacArr, const int *nlArr);
GMO_FUNCPTR(gmoAddRow);
typedef int  (GMO_CALLCONV *gmoAddCol_t) (gmoHandle_t pgmo, int typVar, double loVar, double lVar, double upVar, double mVar, int basVar, int sosVar, double priorVar, double scaleVar, int nzVar, const int *rowArr, const double *jacArr, const int *nlArr);
GMO_FUNCPTR(gmoAddCol);
typedef void  (GMO_CALLCONV *gmoCompleteJacs_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoCompleteJacs);
typedef int  (GMO_CALLCONV *gmoCrudeness_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoCrudeness);
typedef void * (GMO_CALLCONV *gmoDict_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoDict);
typedef void * (GMO_CALLCONV *gmoEnvironment_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoEnvironment);
typedef int  (GMO_CALLCONV *gmoRegisterEnvironment_t) (gmoHandle_t pgmo, void *gevPtr, char *msg);
GMO_FUNCPTR(gmoRegisterEnvironment);
typedef int  (GMO_CALLCONV *gmoEvalGradNLInt_t) (gmoHandle_t pgmo, double *rhsdelta, int storejacupd, int *numErr);
GMO_FUNCPTR(gmoEvalGradNLInt);
typedef int  (GMO_CALLCONV *gmoGetJacUpdate_t) (gmoHandle_t pgmo, int *ivec, int *jvec, double *JacValue, int *nrjacupd);
GMO_FUNCPTR(gmoGetJacUpdate);
typedef int  (GMO_CALLCONV *gmoGetSolveStatusTxt_t) (gmoHandle_t pgmo, int solvestat, char *sstxt);
GMO_FUNCPTR(gmoGetSolveStatusTxt);
typedef int  (GMO_CALLCONV *gmoGetModelStatusTxt_t) (gmoHandle_t pgmo, int modelstat, char *mstxt);
GMO_FUNCPTR(gmoGetModelStatusTxt);
typedef int  (GMO_CALLCONV *gmoGetModelTypeTxt_t) (gmoHandle_t pgmo, char *mttxt);
GMO_FUNCPTR(gmoGetModelTypeTxt);
typedef int  (GMO_CALLCONV *gmoGetHeadNTailTxt_t) (gmoHandle_t pgmo, int htrec, char *httxt);
GMO_FUNCPTR(gmoGetHeadNTailTxt);
typedef int  (GMO_CALLCONV *gmoDirtyGetRowFNLInstr_t) (gmoHandle_t pgmo, int si, int *len, int *opcode, int *field);
GMO_FUNCPTR(gmoDirtyGetRowFNLInstr);
typedef int  (GMO_CALLCONV *gmoDirtyGetObjFNLInstr_t) (gmoHandle_t pgmo, int *len, int *opcode, int *field);
GMO_FUNCPTR(gmoDirtyGetObjFNLInstr);
typedef int  (GMO_CALLCONV *gmoDirtySetRowFNLInstr_t) (gmoHandle_t pgmo, int si, int len, const int *opcode, const int *field, void *poolx);
GMO_FUNCPTR(gmoDirtySetRowFNLInstr);
typedef int  (GMO_CALLCONV *gmoSetNLObject_t) (gmoHandle_t pgmo, void *NLObj, void *NLPool);
GMO_FUNCPTR(gmoSetNLObject);
typedef int  (GMO_CALLCONV *gmoHessLoad_t) (gmoHandle_t pgmo, int maxJacMult, int *do2dir, int *doHess);
GMO_FUNCPTR(gmoHessLoad);
typedef int  (GMO_CALLCONV *gmoHessUnload_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoHessUnload);
typedef int  (GMO_CALLCONV *gmoHessDim_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoHessDim);
typedef int  (GMO_CALLCONV *gmoHessNz_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoHessNz);
typedef int  (GMO_CALLCONV *gmoHessStruct_t) (gmoHandle_t pgmo, int si, int *HRindex, int *HCindex, int *HessDim, int *HessNz);
GMO_FUNCPTR(gmoHessStruct);
typedef int  (GMO_CALLCONV *gmoHessValue_t) (gmoHandle_t pgmo, int si, int *HRindex, int *HCindex, int *HessDim, int *HessNz, const double *Xval, double *Hval, int *numErr);
GMO_FUNCPTR(gmoHessValue);
typedef int  (GMO_CALLCONV *gmoHessVec_t) (gmoHandle_t pgmo, int si, const double *X, const double *dx, double *Wdx, int *numErr);
GMO_FUNCPTR(gmoHessVec);
typedef int  (GMO_CALLCONV *gmoHessLagStruct_t) (gmoHandle_t pgmo, int *WRindex, int *WCindex);
GMO_FUNCPTR(gmoHessLagStruct);
typedef int  (GMO_CALLCONV *gmoHessLagValue_t) (gmoHandle_t pgmo, const double *X, const double *u, double *w, double objWeight, double conWeight, int *numErr);
GMO_FUNCPTR(gmoHessLagValue);
typedef int  (GMO_CALLCONV *gmoHessLagVec_t) (gmoHandle_t pgmo, const double *X, const double *u, const double *dx, double *Wdx, double objWeight, double conWeight, int *numErr);
GMO_FUNCPTR(gmoHessLagVec);
typedef int  (GMO_CALLCONV *gmoPrepareAllSolToGDX_t) (gmoHandle_t pgmo, const char *gdxfname, void *scengdx, int dictid);
GMO_FUNCPTR(gmoPrepareAllSolToGDX);
typedef int  (GMO_CALLCONV *gmoAddSolutionToGDX_t) (gmoHandle_t pgmo, const char *scenuel);
GMO_FUNCPTR(gmoAddSolutionToGDX);
typedef int  (GMO_CALLCONV *gmoWriteSolDone_t) (gmoHandle_t pgmo, char *msg);
GMO_FUNCPTR(gmoWriteSolDone);
typedef void * (GMO_CALLCONV *gmoViewStore_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoViewStore);
typedef void  (GMO_CALLCONV *gmoViewRestore_t) (gmoHandle_t pgmo, void **viewptr);
GMO_FUNCPTR(gmoViewRestore);
typedef int  (GMO_CALLCONV *gmoLoadEMPInfo_t) (gmoHandle_t pgmo, const char *empinfofn);
GMO_FUNCPTR(gmoLoadEMPInfo);
typedef int  (GMO_CALLCONV *gmoGetEquVI_t) (gmoHandle_t pgmo, int *Mvector);
GMO_FUNCPTR(gmoGetEquVI);
typedef int  (GMO_CALLCONV *gmoGetEquVIOne_t) (gmoHandle_t pgmo, int si);
GMO_FUNCPTR(gmoGetEquVIOne);
typedef int  (GMO_CALLCONV *gmoGetVarVI_t) (gmoHandle_t pgmo, int *Nvector);
GMO_FUNCPTR(gmoGetVarVI);
typedef int  (GMO_CALLCONV *gmoGetVarVIOne_t) (gmoHandle_t pgmo, int sj);
GMO_FUNCPTR(gmoGetVarVIOne);
typedef int  (GMO_CALLCONV *gmoGetAgentType_t) (gmoHandle_t pgmo, int *NumAgentVector);
GMO_FUNCPTR(gmoGetAgentType);
typedef int  (GMO_CALLCONV *gmoGetAgentTypeOne_t) (gmoHandle_t pgmo, int a);
GMO_FUNCPTR(gmoGetAgentTypeOne);
typedef int  (GMO_CALLCONV *gmoGetBiLevelInfo_t) (gmoHandle_t pgmo, int *Nvector, int *Mvector);
GMO_FUNCPTR(gmoGetBiLevelInfo);
typedef char * (GMO_CALLCONV *gmoNameModel_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameModel);
typedef void (GMO_CALLCONV *gmoNameModelSet_t) (gmoHandle_t pgmo, const char *x);
GMO_FUNCPTR(gmoNameModelSet);
typedef int  (GMO_CALLCONV *gmoObjNZ_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjNZ);
typedef int  (GMO_CALLCONV *gmoObjNLNZ_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjNLNZ);
typedef int  (GMO_CALLCONV *gmoObjStyle_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjStyle);
typedef void (GMO_CALLCONV *gmoObjStyleSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoObjStyleSet);
typedef int  (GMO_CALLCONV *gmoGetObjOrder_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoGetObjOrder);
typedef int  (GMO_CALLCONV *gmoErrorMethod_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoErrorMethod);
typedef void (GMO_CALLCONV *gmoErrorMethodSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoErrorMethodSet);
typedef int  (GMO_CALLCONV *gmoInterface_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoInterface);
typedef void (GMO_CALLCONV *gmoInterfaceSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoInterfaceSet);
typedef int  (GMO_CALLCONV *gmoIndexBase_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoIndexBase);
typedef void (GMO_CALLCONV *gmoIndexBaseSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoIndexBaseSet);
typedef int  (GMO_CALLCONV *gmoObjReform_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjReform);
typedef void (GMO_CALLCONV *gmoObjReformSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoObjReformSet);
typedef int  (GMO_CALLCONV *gmoEmptyOut_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoEmptyOut);
typedef void (GMO_CALLCONV *gmoEmptyOutSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoEmptyOutSet);
typedef double  (GMO_CALLCONV *gmoObjConst_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjConst);
typedef double  (GMO_CALLCONV *gmoObjJacVal_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjJacVal);
typedef int  (GMO_CALLCONV *gmoModelStat_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoModelStat);
typedef void (GMO_CALLCONV *gmoModelStatSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoModelStatSet);
typedef int  (GMO_CALLCONV *gmoSolveStat_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoSolveStat);
typedef void (GMO_CALLCONV *gmoSolveStatSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoSolveStatSet);
typedef double  (GMO_CALLCONV *gmoPinf_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoPinf);
typedef void (GMO_CALLCONV *gmoPinfSet_t) (gmoHandle_t pgmo, const double x);
GMO_FUNCPTR(gmoPinfSet);
typedef double  (GMO_CALLCONV *gmoMinf_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoMinf);
typedef void (GMO_CALLCONV *gmoMinfSet_t) (gmoHandle_t pgmo, const double x);
GMO_FUNCPTR(gmoMinfSet);
typedef double  (GMO_CALLCONV *gmoInfTol_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoInfTol);
typedef void (GMO_CALLCONV *gmoInfTolSet_t) (gmoHandle_t pgmo, const double x);
GMO_FUNCPTR(gmoInfTolSet);
typedef double  (GMO_CALLCONV *gmoOptTol_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoOptTol);
typedef void (GMO_CALLCONV *gmoOptTolSet_t) (gmoHandle_t pgmo, const double x);
GMO_FUNCPTR(gmoOptTolSet);
typedef int  (GMO_CALLCONV *gmoAltBounds_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoAltBounds);
typedef void (GMO_CALLCONV *gmoAltBoundsSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoAltBoundsSet);
typedef int  (GMO_CALLCONV *gmoAltRHS_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoAltRHS);
typedef void (GMO_CALLCONV *gmoAltRHSSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoAltRHSSet);
typedef int  (GMO_CALLCONV *gmoAltVarTypes_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoAltVarTypes);
typedef void (GMO_CALLCONV *gmoAltVarTypesSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoAltVarTypesSet);
typedef int  (GMO_CALLCONV *gmoForceLinear_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoForceLinear);
typedef void (GMO_CALLCONV *gmoForceLinearSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoForceLinearSet);
typedef int  (GMO_CALLCONV *gmoForceCont_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoForceCont);
typedef void (GMO_CALLCONV *gmoForceContSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoForceContSet);
typedef int  (GMO_CALLCONV *gmoIsQP_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoIsQP);
typedef int  (GMO_CALLCONV *gmoNDisc_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNDisc);
typedef int  (GMO_CALLCONV *gmoMaxQnz_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoMaxQnz);
typedef int  (GMO_CALLCONV *gmoQRows_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoQRows);
typedef int  (GMO_CALLCONV *gmoWantQ_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoWantQ);
typedef void (GMO_CALLCONV *gmoWantQSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoWantQSet);
typedef int  (GMO_CALLCONV *gmoObjQNZ_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjQNZ);
typedef int  (GMO_CALLCONV *gmoObjQDiagNZ_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjQDiagNZ);
typedef int  (GMO_CALLCONV *gmoNLCodeFun_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNLCodeFun);
typedef void (GMO_CALLCONV *gmoNLCodeFunSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoNLCodeFunSet);
typedef int  (GMO_CALLCONV *gmoMaxSingleFNL_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoMaxSingleFNL);
typedef void * (GMO_CALLCONV *gmoPCodeFun_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoPCodeFun);
typedef void * (GMO_CALLCONV *gmoPPool_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoPPool);
typedef int  (GMO_CALLCONV *gmoNFixed_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNFixed);
typedef int  (GMO_CALLCONV *gmoPermuteCols_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoPermuteCols);
typedef void (GMO_CALLCONV *gmoPermuteColsSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoPermuteColsSet);
typedef int  (GMO_CALLCONV *gmoPermuteRows_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoPermuteRows);
typedef void (GMO_CALLCONV *gmoPermuteRowsSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoPermuteRowsSet);
typedef int  (GMO_CALLCONV *gmoMaxThreads_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoMaxThreads);
typedef void (GMO_CALLCONV *gmoMaxThreadsSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoMaxThreadsSet);
typedef double  (GMO_CALLCONV *gmoQNaN_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoQNaN);
typedef double  (GMO_CALLCONV *gmoValNA_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoValNA);
typedef int  (GMO_CALLCONV *gmoValNAInt_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoValNAInt);
typedef int  (GMO_CALLCONV *gmoIgnXCDeriv_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoIgnXCDeriv);
typedef void (GMO_CALLCONV *gmoIgnXCDerivSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoIgnXCDerivSet);
typedef int  (GMO_CALLCONV *gmoHessMaxDim_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoHessMaxDim);
typedef int  (GMO_CALLCONV *gmoHessMaxNz_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoHessMaxNz);
typedef int  (GMO_CALLCONV *gmoHessLagDim_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoHessLagDim);
typedef int  (GMO_CALLCONV *gmoHessLagNz_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoHessLagNz);
typedef int  (GMO_CALLCONV *gmoHessLagDiagNz_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoHessLagDiagNz);
typedef int  (GMO_CALLCONV *gmoNumVIFunc_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNumVIFunc);
typedef int  (GMO_CALLCONV *gmoNumAgents_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNumAgents);
typedef int  (GMO_CALLCONV *gmoModelType_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoModelType);
typedef void (GMO_CALLCONV *gmoModelTypeSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoModelTypeSet);
typedef int  (GMO_CALLCONV *gmoM_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoM);
typedef int  (GMO_CALLCONV *gmoN_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoN);
typedef int  (GMO_CALLCONV *gmoScaleOpt_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoScaleOpt);
typedef void (GMO_CALLCONV *gmoScaleOptSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoScaleOptSet);
typedef int  (GMO_CALLCONV *gmoSense_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoSense);
typedef void (GMO_CALLCONV *gmoSenseSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoSenseSet);
typedef int  (GMO_CALLCONV *gmoObjVar_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjVar);
typedef void (GMO_CALLCONV *gmoObjVarSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoObjVarSet);
typedef int  (GMO_CALLCONV *gmoOptFile_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoOptFile);
typedef void (GMO_CALLCONV *gmoOptFileSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoOptFileSet);
typedef int  (GMO_CALLCONV *gmoPriorOpt_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoPriorOpt);
typedef void (GMO_CALLCONV *gmoPriorOptSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoPriorOptSet);
typedef int  (GMO_CALLCONV *gmoNLConst_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNLConst);
typedef void (GMO_CALLCONV *gmoNLConstSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoNLConstSet);
typedef int  (GMO_CALLCONV *gmoNZ_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNZ);
typedef void (GMO_CALLCONV *gmoNZSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoNZSet);
typedef int  (GMO_CALLCONV *gmoNLNZ_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNLNZ);
typedef int  (GMO_CALLCONV *gmoNLM_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNLM);
typedef int  (GMO_CALLCONV *gmoNLN_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoNLN);
typedef int  (GMO_CALLCONV *gmoObjRow_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoObjRow);
typedef int  (GMO_CALLCONV *gmoDictionary_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoDictionary);
typedef void (GMO_CALLCONV *gmoDictionarySet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoDictionarySet);
typedef int  (GMO_CALLCONV *gmoHaveBasis_t) (gmoHandle_t pgmo);
GMO_FUNCPTR(gmoHaveBasis);
typedef void (GMO_CALLCONV *gmoHaveBasisSet_t) (gmoHandle_t pgmo, const int x);
GMO_FUNCPTR(gmoHaveBasisSet);
typedef char * (GMO_CALLCONV *gmoNameOptFile_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameOptFile);
typedef void (GMO_CALLCONV *gmoNameOptFileSet_t) (gmoHandle_t pgmo, const char *x);
GMO_FUNCPTR(gmoNameOptFileSet);
typedef char * (GMO_CALLCONV *gmoNameSolFile_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameSolFile);
typedef void (GMO_CALLCONV *gmoNameSolFileSet_t) (gmoHandle_t pgmo, const char *x);
GMO_FUNCPTR(gmoNameSolFileSet);
typedef char * (GMO_CALLCONV *gmoNameXLib_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameXLib);
typedef void (GMO_CALLCONV *gmoNameXLibSet_t) (gmoHandle_t pgmo, const char *x);
GMO_FUNCPTR(gmoNameXLibSet);
typedef char * (GMO_CALLCONV *gmoNameMatFile_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameMatFile);
typedef void (GMO_CALLCONV *gmoNameMatFileSet_t) (gmoHandle_t pgmo, const char *x);
GMO_FUNCPTR(gmoNameMatFileSet);
typedef char * (GMO_CALLCONV *gmoNameDict_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameDict);
typedef void (GMO_CALLCONV *gmoNameDictSet_t) (gmoHandle_t pgmo, const char *x);
GMO_FUNCPTR(gmoNameDictSet);
typedef char * (GMO_CALLCONV *gmoNameParams_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameParams);
typedef void (GMO_CALLCONV *gmoNameParamsSet_t) (gmoHandle_t pgmo, const char *x);
GMO_FUNCPTR(gmoNameParamsSet);
typedef char * (GMO_CALLCONV *gmoNameInput_t) (gmoHandle_t pgmo, char *buf);
GMO_FUNCPTR(gmoNameInput);
#if defined(__cplusplus)
}
#endif
#endif /* #if ! defined(_GMOCC_H_) */
